# Generated by Django 4.2 on 2025-11-24 20:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_populate_section_and_action_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTemplateFieldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('template_code', models.CharField(help_text='Cached template code', max_length=30, verbose_name='Template Code')),
                ('event_type', models.CharField(choices=[('on_change', 'On Change'), ('on_set', 'On Set'), ('on_clear', 'On Clear')], max_length=30, verbose_name='Event Type')),
                ('event_order', models.PositiveSmallIntegerField(default=0, help_text='Execution order for multiple events', verbose_name='Event Order')),
                ('action_reference', models.CharField(help_text='Entity Reference System action to execute', max_length=255, verbose_name='Action Reference')),
                ('condition_rules', models.JSONField(blank=True, default=dict, help_text='JSON rules for conditional execution based on field value', verbose_name='Condition Rules')),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1, verbose_name='Is Enabled')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Cached template reference', on_delete=django.db.models.deletion.CASCADE, related_name='field_events', to='ticketing.tickettemplate', verbose_name='Template')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.tickettemplatefield', verbose_name='Template Field')),
            ],
            options={
                'verbose_name': 'Template Field Event',
                'verbose_name_plural': 'Template Field Events',
                'ordering': ('template_field', 'event_type', 'event_order'),
            },
        ),
        migrations.CreateModel(
            name='TicketTemplateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('template_code', models.CharField(help_text='Cached template code', max_length=30, verbose_name='Template Code')),
                ('event_type', models.CharField(choices=[('on_open', 'On Open'), ('on_close', 'On Close'), ('on_respond', 'On Respond'), ('on_status_change', 'On Status Change'), ('on_assigned', 'On Assigned'), ('on_resolved', 'On Resolved')], max_length=30, verbose_name='Event Type')),
                ('event_order', models.PositiveSmallIntegerField(default=0, help_text='Execution order for multiple events of the same type', verbose_name='Event Order')),
                ('action_reference', models.CharField(help_text="Entity Reference System action (e.g., 'users:show:gp=superuser', '0270:approve:code={ticket.reference_code}')", max_length=255, verbose_name='Action Reference')),
                ('condition_rules', models.JSONField(blank=True, default=dict, help_text="JSON rules for conditional execution (e.g., {'field_key': 'priority', 'operator': 'equals', 'value': 'high'})", verbose_name='Condition Rules')),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1, verbose_name='Is Enabled')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ticketing.tickettemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Event',
                'verbose_name_plural': 'Template Events',
                'ordering': ('template', 'event_type', 'event_order'),
            },
        ),
        migrations.AddIndex(
            model_name='tickettemplatefieldevent',
            index=models.Index(fields=['template_field', 'event_type', 'event_order'], name='tkt_field_event_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettemplateevent',
            index=models.Index(fields=['template', 'event_type', 'event_order'], name='tkt_tmpl_event_type_order_idx'),
        ),
    ]
