# Generated by Django 4.2 on 2025-11-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0002_add_template_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
    ]
