# Generated by Django 4.2 on 2025-11-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_workcenter_public_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bommaterial',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='bommaterial',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='orderperformance',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='orderperformance',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='transfertoline',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='transfertoline',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='transfertolineitem',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='transfertolineitem',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='deactivated_at',
        ),
    ]
