# Generated by Django 4.2 on 2025-11-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_bom_company_code_bom_disabled_at_bom_disabled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='material_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('semi-finished', 'Semi-Finished'), ('component', 'Component'), ('packaging', 'Packaging')], default='raw', max_length=30),
        ),
    ]
