# Generated by Django 4.2 on 2025-11-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_person_from_inventory'),
        ('production', '0008_alter_bommaterial_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='material_type',
            field=models.ForeignKey(help_text='Type/category of the material', on_delete=django.db.models.deletion.PROTECT, related_name='bom_materials', to='inventory.itemtype', verbose_name='Material Type'),
        ),
    ]
