# Generated by Django 4.2 on 2025-11-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_person_from_inventory'),
        ('production', '0009_bom_material_type_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measurement for this material', on_delete=django.db.models.deletion.PROTECT, related_name='bom_materials', to='inventory.itemunit', verbose_name='Unit'),
        ),
    ]
