# Generated by Django 4.2 on 2025-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_bom_unit_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='unit',
            field=models.CharField(help_text='Unit of measurement for this material', max_length=50, verbose_name='Unit'),
        ),
    ]
