# Generated by Django 4.2 on 2025-11-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_bom_unit_back_to_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='expiry_date',
        ),
    ]
