# Generated by Django 4.2 on 2025-11-20 23:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_move_workline_to_production'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0009_remove_personassignment_company_and_more'),
        ('production', '0012_bom_remove_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('public_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('name', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('machines', models.ManyToManyField(blank=True, help_text='Machines assigned to this work line', related_name='work_lines', to='production.machine')),
                ('personnel', models.ManyToManyField(blank=True, help_text='Personnel assigned to this work line', related_name='work_lines', to='production.person')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse (optional, only if inventory module is installed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Work Line',
                'verbose_name_plural': 'Work Lines',
                'ordering': ('company', 'warehouse', 'sort_order', 'public_code'),
            },
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('company', 'warehouse', 'public_code'), name='production_work_line_public_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('company', 'public_code'), name='production_work_line_public_code_unique_no_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('company', 'warehouse', 'name'), name='production_work_line_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='workline',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', True)), fields=('company', 'name'), name='production_work_line_name_unique_no_warehouse'),
        ),
    ]
