# Generated by Django 4.2 on 2025-11-20 23:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_move_workline_to_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='bom',
            field=models.ForeignKey(blank=True, help_text='Bill of Materials for this process', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='production.bom'),
        ),
        migrations.AddField(
            model_name='process',
            name='work_lines',
            field=models.ManyToManyField(blank=True, help_text='Work lines assigned to this process', related_name='processes', to='production.workline'),
        ),
        migrations.AlterField(
            model_name='process',
            name='bom_code',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_code',
            field=models.CharField(editable=False, max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
