# Generated by Django 4.2 on 2025-11-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_update_process_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='process',
            name='production_process_revision_unique',
        ),
        migrations.AlterField(
            model_name='process',
            name='revision',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(condition=models.Q(('revision__isnull', False), models.Q(('revision', ''), _negated=True)), fields=('company', 'finished_item', 'revision'), name='production_process_revision_unique'),
        ),
    ]
