# Generated by Django 4.2 on 2025-11-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_remove_effective_dates_from_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='process',
            name='effective_to',
        ),
    ]
