# Generated by Django 4.2 on 2025-11-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_effective_dates_from_process'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='process',
            name='production_process_revision_unique',
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(condition=models.Q(('revision', ''), _negated=True), fields=('company', 'finished_item', 'revision'), name='production_process_revision_unique'),
        ),
    ]
