# Generated by Django 4.2 on 2025-11-20 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0017_fix_process_revision_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
