# Generated by Django 4.2 on 2025-11-22 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0019_add_bom_and_approved_by_to_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertoline',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who can approve this transfer request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='is_locked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertolineitem',
            name='is_extra',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='Whether this item is an extra request (not from BOM)', verbose_name='Extra Request'),
        ),
        migrations.AlterField(
            model_name='transfertoline',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='transfertolineitem',
            name='destination_work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='production.workcenter'),
        ),
    ]
