# Generated by Django 4.2 on 2025-11-28 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0022_add_process_operations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processoperation',
            new_name='production__process_42c13b_idx',
            old_name='production__process_sequence_idx',
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='transfertoline',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
    ]
