# Generated by Django 4.2 on 2025-11-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0023_rename_production__process_sequence_idx_production__process_42c13b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bom',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='bom',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='bommaterial',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bommaterial',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='bommaterial',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='machine',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='orderperformance',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderperformance',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='orderperformance',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='performancerecordmachine',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancerecordmachine',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='performancerecordmachine',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='performancerecordmaterial',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancerecordmaterial',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='performancerecordmaterial',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='performancerecordperson',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancerecordperson',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='performancerecordperson',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='process',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='processoperation',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processoperation',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='processoperation',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='processoperationmaterial',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processoperationmaterial',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='processoperationmaterial',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processstep',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='processstep',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productorder',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='productorder',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='transfertolineitem',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertolineitem',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='transfertolineitem',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='workline',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workline',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='workline',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
    ]
