# Generated by Django 4.2 on 2025-12-03 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_add_warehouse_transfer_issue'),
        ('production', '0027_add_qc_approval_fields_to_transfer_to_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='bommaterial',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, help_text='The warehouse from which this material should be transferred (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_materials', to='inventory.warehouse', verbose_name='Source Warehouse'),
        ),
        migrations.AddField(
            model_name='bommaterial',
            name='source_warehouse_code',
            field=models.CharField(blank=True, help_text='Warehouse code for reference', max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
