# Generated by Django 4.2 on 2025-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_add_source_warehouse_to_bom_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='bommaterial',
            name='source_warehouses',
            field=models.JSONField(blank=True, default=list, help_text="List of source warehouses with priorities. Format: [{'warehouse_id': 1, 'warehouse_code': '001', 'priority': 1}, ...]", verbose_name='Source Warehouses'),
        ),
    ]
