# Generated by Django 4.2 on 2025-12-04 11:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0015_add_primary_groups_to_user'),
        ('inventory', '0044_link_existing_warehouse_transfers'),
        ('production', '0030_change_destination_work_center_to_workline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMMaterialAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('alternative_item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Alternative Item Code')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Required quantity of the alternative item (can differ from main material quantity)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity')),
                ('unit', models.CharField(help_text="Unit of measurement for this alternative item (must be from alternative item's allowed units)", max_length=50, verbose_name='Unit')),
                ('priority', models.PositiveSmallIntegerField(help_text='Priority order for using this alternative (1 = highest priority, must be unique per BOM material)', verbose_name='Priority')),
                ('source_warehouses', models.JSONField(blank=True, default=list, help_text="List of source warehouses with priorities (1-5 warehouses). Format: [{'warehouse_id': 1, 'warehouse_code': '001', 'priority': 1}, ...]", verbose_name='Source Warehouses')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('alternative_item', models.ForeignKey(help_text='The alternative item that can replace the main material', on_delete=django.db.models.deletion.PROTECT, related_name='bom_material_alternatives', to='inventory.item', verbose_name='Alternative Item')),
                ('bom_material', models.ForeignKey(help_text='The BOM material line this alternative belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='production.bommaterial', verbose_name='BOM Material')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOM Material Alternative',
                'verbose_name_plural': 'BOM Material Alternatives',
                'ordering': ('bom_material', 'priority'),
            },
        ),
        migrations.AddConstraint(
            model_name='bommaterialalternative',
            constraint=models.UniqueConstraint(fields=('bom_material', 'priority'), name='production_bom_material_alternative_priority_unique'),
        ),
        migrations.AddConstraint(
            model_name='bommaterialalternative',
            constraint=models.UniqueConstraint(fields=('bom_material', 'alternative_item'), name='production_bom_material_alternative_item_unique'),
        ),
    ]
