# Generated by Django 4.2 on 2025-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_add_bom_material_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='bommaterialalternative',
            name='is_combinable',
            field=models.PositiveSmallIntegerField(default=0, help_text='Whether this alternative item can be combined with other alternatives (0 = No, 1 = Yes)', verbose_name='Combinable'),
        ),
    ]
