# Generated by Django 4.2 on 2025-12-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_add_is_combinable_to_bom_material_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerecord',
            name='document_type',
            field=models.CharField(choices=[('operational', 'Operational'), ('general', 'General')], default='operational', help_text='Type of performance record: Operational (for specific operation) or General (for entire order)', max_length=20, verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='operation',
            field=models.ForeignKey(blank=True, help_text='The process operation this performance record is for (only for operational documents)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to='production.processoperation', verbose_name='Process Operation'),
        ),
        migrations.AddConstraint(
            model_name='performancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'operational'), ('operation__isnull', False)), fields=('company', 'order', 'operation'), name='production_performance_operational_unique'),
        ),
        migrations.AddConstraint(
            model_name='performancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'general')), fields=('company', 'order'), name='production_performance_general_unique'),
        ),
    ]
