# Generated by Django 4.2 on 2025-12-05 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0015_add_primary_groups_to_user'),
        ('production', '0034_add_requires_qc_to_process_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReworkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('rework_code', models.CharField(max_length=30, unique=True, verbose_name='Rework Code')),
                ('order_code', models.CharField(max_length=30)),
                ('rework_date', models.DateField(default=django.utils.timezone.now, verbose_name='Rework Date')),
                ('reason', models.TextField(help_text='Reason for rework', verbose_name='Rework Reason')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this rework document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rework_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, help_text='The operation this rework is for (null if rework is for operations without performance documents)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_documents', to='production.processoperation', verbose_name='Process Operation')),
                ('order', models.ForeignKey(help_text='The production order this rework document belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='rework_documents', to='production.productorder', verbose_name='Product Order')),
                ('original_performance', models.ForeignKey(blank=True, help_text='The original performance record that was rejected by QC (null if operation had no performance document)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_documents', to='production.performancerecord', verbose_name='Original Performance Record')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rework Document',
                'verbose_name_plural': 'Rework Documents',
                'ordering': ('-rework_date', 'rework_code'),
            },
        ),
        migrations.CreateModel(
            name='OperationQCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('order_code', models.CharField(max_length=30)),
                ('performance_code', models.CharField(max_length=30)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current QC approval status', max_length=20, verbose_name='QC Status')),
                ('qc_status_date', models.DateTimeField(blank=True, null=True, verbose_name='QC Status Date')),
                ('qc_notes', models.TextField(blank=True, help_text='Notes from QC reviewer', verbose_name='QC Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(help_text='The operation this QC status is for', on_delete=django.db.models.deletion.CASCADE, related_name='qc_statuses', to='production.processoperation', verbose_name='Process Operation')),
                ('order', models.ForeignKey(help_text='The production order this QC status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='operation_qc_statuses', to='production.productorder', verbose_name='Product Order')),
                ('performance', models.ForeignKey(help_text='The performance document for this operation', on_delete=django.db.models.deletion.CASCADE, related_name='qc_statuses', to='production.performancerecord', verbose_name='Performance Record')),
                ('qc_approved_by', models.ForeignKey(blank=True, help_text='User who approved/rejected this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved_operations', to=settings.AUTH_USER_MODEL, verbose_name='QC Approver')),
            ],
            options={
                'verbose_name': 'Operation QC Status',
                'verbose_name_plural': 'Operation QC Statuses',
                'ordering': ('-qc_status_date', 'order', 'operation'),
            },
        ),
        migrations.AddIndex(
            model_name='reworkdocument',
            index=models.Index(fields=['order', 'rework_date'], name='production__order_i_9d0575_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkdocument',
            index=models.Index(fields=['status', 'rework_date'], name='production__status_98ce50_idx'),
        ),
        migrations.AddIndex(
            model_name='operationqcstatus',
            index=models.Index(fields=['order', 'operation', 'qc_status'], name='production__order_i_ac9068_idx'),
        ),
        migrations.AddIndex(
            model_name='operationqcstatus',
            index=models.Index(fields=['qc_status', 'qc_status_date'], name='production__qc_stat_796b70_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationqcstatus',
            constraint=models.UniqueConstraint(fields=('company', 'order', 'operation', 'performance'), name='production_operation_qc_status_unique'),
        ),
    ]
