# Generated by Django 4.2 on 2025-11-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_company',
            field=models.ForeignKey(blank=True, help_text='Default company to use when user logs in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='shared.company'),
        ),
    ]
