# Generated by Django 4.2 on 2025-11-09 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_user_default_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='public_code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
