# Generated by Django 4.2 on 2025-11-09 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_company_public_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyunit',
            name='public_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
