# Generated by Django 4.2 on 2025-11-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_alter_companyunit_public_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevel',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='accesslevel',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='companyunit',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='companyunit',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='usercompanyaccess',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='usercompanyaccess',
            name='deactivated_at',
        ),
    ]
