# Generated by Django 4.2 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_alter_receiptinspection_approved_by_and_more'),
        ('production', '0005_person_processstep_machine_code_personassignment_and_more'),
        ('inventory', '0022_alter_purchaserequest_approver_and_more'),
        ('shared', '0008_5_migrate_person_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personassignment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='enabled_by',
        ),
        migrations.RemoveField(
            model_name='personassignment',
            name='person',
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonAssignment',
        ),
    ]
