# Generated by Django 4.2 on 2025-11-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_remove_personassignment_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(help_text='A descriptive name for this SMTP server configuration', max_length=120, unique=True, verbose_name='Server Name')),
                ('host', models.CharField(help_text='SMTP server hostname or IP address (e.g., smtp.gmail.com)', max_length=255, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP server port (usually 587 for TLS, 465 for SSL, 25 for plain)', verbose_name='SMTP Port')),
                ('use_tls', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1, help_text='Enable TLS encryption for SMTP connection', verbose_name='Use TLS')),
                ('use_ssl', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='Enable SSL encryption for SMTP connection (usually for port 465)', verbose_name='Use SSL')),
                ('username', models.CharField(help_text='SMTP authentication username (usually email address)', max_length=255, verbose_name='Username')),
                ('password', models.CharField(help_text='SMTP authentication password or app-specific password', max_length=255, verbose_name='Password')),
                ('from_email', models.EmailField(help_text='Default sender email address', max_length=255, verbose_name='From Email')),
                ('from_name', models.CharField(blank=True, help_text='Default sender name (optional)', max_length=120, verbose_name='From Name')),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Connection timeout in seconds', verbose_name='Connection Timeout')),
                ('description', models.TextField(blank=True, help_text='Additional notes about this SMTP configuration', verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMTP Server',
                'verbose_name_plural': 'SMTP Servers',
                'ordering': ('name',),
            },
        ),
    ]
