# Generated by Django 4.2 on 2025-11-24 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_smtpserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('section_code', models.CharField(help_text='6-digit code in XXYYZZ format (module + menu + submenu)', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Section code must be exactly 6 digits.', regex='^\\d{6}$')], verbose_name='Section Code')),
                ('nickname', models.CharField(help_text="Unique identifier for this section (e.g., 'users', 'purchase_requests')", max_length=50, unique=True, verbose_name='Nickname')),
                ('module_code', models.CharField(help_text='2-digit module number (00=dashboard, 01=shared, 02=inventory, etc.)', max_length=2, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Module Code')),
                ('menu_number', models.CharField(help_text='2-digit menu number within module', max_length=2, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Menu Number')),
                ('submenu_number', models.CharField(blank=True, help_text='2-digit submenu number (NULL if no submenu)', max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Submenu Number')),
                ('name', models.CharField(help_text='Display name in local language', max_length=180, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, help_text='Display name in English', max_length=180, verbose_name='Name (English)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(help_text="Module identifier (e.g., 'shared', 'inventory')", max_length=30, verbose_name='Module')),
                ('app_label', models.CharField(help_text="Django app label (e.g., 'shared', 'inventory')", max_length=30, verbose_name='App Label')),
                ('list_url_name', models.CharField(blank=True, help_text="Django URL name for list view (e.g., 'inventory:items')", max_length=100, null=True, verbose_name='List URL Name')),
                ('detail_url_name', models.CharField(blank=True, help_text="Django URL name for detail/edit view (e.g., 'inventory:item_edit')", max_length=100, null=True, verbose_name='Detail URL Name')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section Registry',
                'verbose_name_plural': 'Section Registry',
                'ordering': ('module_code', 'menu_number', 'submenu_number', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='ActionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('action_name', models.CharField(help_text="Action identifier (e.g., 'show', 'approve', 'delete')", max_length=50, verbose_name='Action Name')),
                ('action_label', models.CharField(help_text='Human-readable label for the action', max_length=180, verbose_name='Action Label')),
                ('action_label_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='Action Label (English)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('handler_function', models.CharField(blank=True, help_text="Fully qualified path to handler (e.g., 'inventory.views.requests.PurchaseRequestApproveView')", max_length=200, null=True, verbose_name='Handler Function')),
                ('url_name', models.CharField(blank=True, help_text="Django URL name for this action (e.g., 'inventory:purchase_request_approve')", max_length=100, null=True, verbose_name='URL Name')),
                ('parameter_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema defining required/optional parameters', verbose_name='Parameter Schema')),
                ('permission_required', models.CharField(blank=True, help_text='Feature permission code required for this action', max_length=100, null=True, verbose_name='Permission Required')),
                ('requires_confirmation', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='Whether this action requires user confirmation', verbose_name='Requires Confirmation')),
                ('is_destructive', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='Flag indicating if this is a destructive action', verbose_name='Is Destructive')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='shared.sectionregistry', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Action Registry',
                'verbose_name_plural': 'Action Registry',
                'ordering': ('section', 'sort_order', 'action_name'),
            },
        ),
        migrations.AddIndex(
            model_name='sectionregistry',
            index=models.Index(fields=['section_code'], name='section_registry_code_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionregistry',
            index=models.Index(fields=['nickname'], name='section_registry_nickname_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionregistry',
            index=models.Index(fields=['module_code', 'is_enabled', 'sort_order'], name='section_registry_module_idx'),
        ),
        migrations.AddIndex(
            model_name='actionregistry',
            index=models.Index(fields=['section', 'is_enabled', 'sort_order'], name='action_registry_section_idx'),
        ),
        migrations.AddIndex(
            model_name='actionregistry',
            index=models.Index(fields=['action_name'], name='action_registry_name_idx'),
        ),
        migrations.AddIndex(
            model_name='actionregistry',
            index=models.Index(fields=['url_name'], name='action_registry_url_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionregistry',
            constraint=models.UniqueConstraint(fields=('section', 'action_name'), name='action_registry_section_action_unique'),
        ),
    ]
