# Generated by Django 4.2 on 2025-11-27 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0012_populate_section_and_action_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(help_text="Type of notification (e.g., 'approval_pending', 'approved')", max_length=50, verbose_name='Notification Type')),
                ('notification_key', models.CharField(help_text="Unique key for this notification (e.g., 'approval_pending_purchase_1')", max_length=100, unique=True, verbose_name='Notification Key')),
                ('message', models.TextField(help_text='Notification message text', verbose_name='Message')),
                ('url_name', models.CharField(help_text='Django URL name to redirect to', max_length=100, verbose_name='URL Name')),
                ('count', models.PositiveIntegerField(default=1, help_text='Number of items in this notification', verbose_name='Count')),
                ('is_read', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='Whether this notification has been read', verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When this notification was read', null=True, verbose_name='Read At')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shared.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notification_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'is_read'], name='notification_company_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_key'], name='notification_key_idx'),
        ),
    ]
