# Generated by Django 4.2 on 2025-11-28 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='accesslevelpermission',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslevelpermission',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='accesslevelpermission',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='companyunit',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyunit',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='companyunit',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
    ]
