# Generated by Django 4.2 on 2025-12-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shared', '0014_add_editable_model_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that define same-group permissions for this user', related_name='primary_users', to='auth.group', verbose_name='Primary Groups'),
        ),
    ]
