# Generated by Django 4.2 on 2025-12-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_add_primary_groups_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entity_type',
            field=models.SmallIntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=2, help_text='نوع مودی: حقیقی (1) یا حقوقی (2)'),
        ),
    ]
