# Generated by Django 4.2 on 2025-11-09 16:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('request_code', models.CharField(max_length=20, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=20)),
                ('warehouse_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('requester_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('department_unit_code', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('request_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_code', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issue_document_id', models.BigIntegerField(blank=True, null=True)),
                ('issue_document_code', models.CharField(blank=True, max_length=20)),
                ('quantity_issued', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_approved', to='shared.person')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_cancelled', to='shared.person')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('department_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests', to='shared.companyunit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to='inventory.item')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_rejected', to='shared.person')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to='shared.person')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Request',
                'verbose_name_plural': 'Warehouse Requests',
                'ordering': ('-request_date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='warehouserequest',
            constraint=models.UniqueConstraint(fields=('company', 'request_code'), name='inventory_warehouse_request_code_unique'),
        ),
    ]
