# Generated by Django 4.2 on 2025-11-09 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouserequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='full_item_code',
            field=models.CharField(blank=True, help_text='16-digit complete code: Type(3) + Category(3) + SubCategory(3) + ItemCode(7)', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, help_text='7-digit code: User(2) + Sequence(5)', max_length=7, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
