# Generated by Django 4.2 on 2025-11-11 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_person_company_units'),
        ('inventory', '0004_remove_issueconsignment_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueconsignment',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_issues', to='shared.companyunit'),
        ),
        migrations.AddField(
            model_name='issueconsignment',
            name='department_unit_code',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_issues', to='shared.companyunit'),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='department_unit_code',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='work_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_issues', to='inventory.workline'),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='work_line_code',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='department_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_issues', to='shared.companyunit'),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='department_unit_code',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
