# Generated by Django 4.2 on 2025-11-11 20:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_issueconsignment_department_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueconsignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issueconsignment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueconsignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issueconsignment_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issueconsumption_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issueconsumption_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issuepermanent_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issuepermanent_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receiptconsignment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='entered_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='entered_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='entered_unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receiptconsignment_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receiptpermanent_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='entered_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='entered_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='entered_unit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receiptpermanent_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipttemporary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipttemporary_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipttemporary',
            name='entered_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receipttemporary',
            name='entered_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='receipttemporary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipttemporary_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
