# Generated by Django 4.2 on 2025-11-12 00:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_groupprofile'),
        ('inventory', '0014_stocktaking_created_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_locked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='warehouse_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_receipts', to='inventory.warehouserequest'),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='warehouse_request_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='warehouse_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_receipts', to='inventory.warehouserequest'),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='warehouse_request_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_to_approve', to='shared.person'),
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='approver_code',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='document_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Document Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Document Date'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='investigation_reference',
            field=models.CharField(blank=True, max_length=30, verbose_name='Investigation Reference'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='is_posted',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Is Posted'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='item_code',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='quantity_adjusted',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Adjusted'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='quantity_counted',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Counted'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Expected'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='reason_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='stocktaking_session_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Stocktaking Session ID'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='valuation_method',
            field=models.CharField(blank=True, max_length=30, verbose_name='Valuation Method'),
        ),
        migrations.AlterField(
            model_name='stocktakingdeficit',
            name='warehouse_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Warehouse Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='approver_notes',
            field=models.TextField(blank=True, verbose_name='Approver Notes'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='confirmation_notes',
            field=models.TextField(blank=True, verbose_name='Confirmation Notes'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='confirmed_by_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Confirmed By Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='document_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Document Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Document Date'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='final_inventory_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Final Value'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='inventory_snapshot_time',
            field=models.DateTimeField(verbose_name='Inventory Snapshot Time'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='record_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Record Metadata'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='stocktaking_session_id',
            field=models.BigIntegerField(verbose_name='Stocktaking Session ID'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='variance_document_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Variance Document Codes'),
        ),
        migrations.AlterField(
            model_name='stocktakingrecord',
            name='variance_document_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Variance Document IDs'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='document_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Document Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='document_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Document Date'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='investigation_reference',
            field=models.CharField(blank=True, max_length=30, verbose_name='Investigation Reference'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='is_posted',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Is Posted'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='item_code',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='quantity_adjusted',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Adjusted'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='quantity_counted',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Counted'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Expected'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='reason_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Reason Code'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='stocktaking_session_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Stocktaking Session ID'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='valuation_method',
            field=models.CharField(blank=True, max_length=30, verbose_name='Valuation Method'),
        ),
        migrations.AlterField(
            model_name='stocktakingsurplus',
            name='warehouse_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Warehouse Code'),
        ),
    ]
