# Generated by Django 4.2 on 2025-11-13 21:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0008_remove_accesslevel_updated_at_and_more'),
        ('inventory', '0016_itemserial_remove_issueconsignment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueconsignment',
            name='consignment_receipt',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='consignment_receipt_code',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='destination_code',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='reason_code',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='serials',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='issueconsignment',
            name='warehouse_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='consumption_type',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='cost_center_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='item',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='production_transfer_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='production_transfer_id',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='reference_document_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='reference_document_id',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='reference_document_type',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='serials',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='warehouse_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='work_line',
        ),
        migrations.RemoveField(
            model_name='issueconsumption',
            name='work_line_code',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='destination_code',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='destination_id',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='destination_type',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='item',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='reason_code',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='serials',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='issuepermanent',
            name='warehouse_code',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='entered_quantity',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='entered_unit',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='entered_unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='unit_price_estimate',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receiptconsignment',
            name='warehouse_code',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='entered_quantity',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='entered_unit',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='entered_unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receiptpermanent',
            name='warehouse_code',
        ),
        migrations.CreateModel(
            name='ReceiptPermanentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('supplier_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('IRT', 'Toman'), ('IRR', 'Rial'), ('USD', 'US Dollar')], max_length=3)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.receiptpermanent')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='receipt_permanent_lines', to='inventory.itemserial')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_receipt_lines', to='inventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Permanent Receipt Line',
                'verbose_name_plural': 'Permanent Receipt Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptConsignmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('supplier_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit_price_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('IRT', 'Toman'), ('IRR', 'Rial'), ('USD', 'US Dollar')], max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.receiptconsignment')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='receipt_consignment_lines', to='inventory.itemserial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_receipt_lines', to='inventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Consignment Receipt Line',
                'verbose_name_plural': 'Consignment Receipt Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IssuePermanentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('destination_type', models.CharField(max_length=30)),
                ('destination_id', models.BigIntegerField(blank=True, null=True)),
                ('destination_code', models.CharField(blank=True, max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(blank=True, choices=[('IRT', 'Toman'), ('IRR', 'Rial'), ('USD', 'US Dollar')], max_length=3)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issuepermanent')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='issue_permanent_lines', to='inventory.itemserial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Permanent Issue Line',
                'verbose_name_plural': 'Permanent Issue Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IssueConsumptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('consumption_type', models.CharField(max_length=30)),
                ('reference_document_type', models.CharField(blank=True, max_length=30)),
                ('reference_document_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_document_code', models.CharField(blank=True, max_length=30)),
                ('production_transfer_id', models.BigIntegerField(blank=True, null=True)),
                ('production_transfer_code', models.CharField(blank=True, max_length=30)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_center_code', models.CharField(blank=True, max_length=30)),
                ('work_line_code', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issueconsumption')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='issue_consumption_lines', to='inventory.itemserial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
                ('work_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_issue_lines', to='inventory.workline')),
            ],
            options={
                'verbose_name': 'Consumption Issue Line',
                'verbose_name_plural': 'Consumption Issue Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IssueConsignmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('consignment_receipt_code', models.CharField(max_length=20)),
                ('destination_type', models.CharField(max_length=30)),
                ('destination_id', models.BigIntegerField(blank=True, null=True)),
                ('destination_code', models.CharField(blank=True, max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('consignment_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='inventory.receiptconsignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issueconsignment')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='issue_consignment_lines', to='inventory.itemserial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Consignment Issue Line',
                'verbose_name_plural': 'Consignment Issue Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='receiptpermanentline',
            index=models.Index(fields=['company', 'document'], name='inv_receipt_perm_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptpermanentline',
            index=models.Index(fields=['company', 'item'], name='inv_receipt_perm_line_item_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptconsignmentline',
            index=models.Index(fields=['company', 'document'], name='inv_rec_consg_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptconsignmentline',
            index=models.Index(fields=['company', 'item'], name='inv_rec_consg_line_item_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepermanentline',
            index=models.Index(fields=['company', 'document'], name='inv_issue_perm_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepermanentline',
            index=models.Index(fields=['company', 'item'], name='inv_issue_perm_line_item_idx'),
        ),
        migrations.AddIndex(
            model_name='issueconsumptionline',
            index=models.Index(fields=['company', 'document'], name='inv_issue_cons_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='issueconsumptionline',
            index=models.Index(fields=['company', 'item'], name='inv_issue_cons_line_item_idx'),
        ),
        migrations.AddIndex(
            model_name='issueconsignmentline',
            index=models.Index(fields=['company', 'document'], name='inv_issue_consg_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='issueconsignmentline',
            index=models.Index(fields=['company', 'item'], name='inv_issue_consg_line_item_idx'),
        ),
    ]
