# Generated by Django 4.2 on 2025-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_issueconsignment_consignment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptconsignmentline',
            name='entered_price_unit',
            field=models.CharField(blank=True, help_text='Unit for entered_unit_price (e.g., BOX, CARTON). If empty, same as entered_unit.', max_length=30),
        ),
        migrations.AddField(
            model_name='receiptpermanentline',
            name='entered_price_unit',
            field=models.CharField(blank=True, help_text='Unit for entered_unit_price (e.g., BOX, CARTON). If empty, same as entered_unit.', max_length=30),
        ),
    ]
