# Generated by Django 4.2 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_change_stocktaking_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptpermanent',
            options={'ordering': ('-id', '-document_date', 'document_code'), 'verbose_name': 'Permanent Receipt', 'verbose_name_plural': 'Permanent Receipts'},
        ),
        migrations.AlterField(
            model_name='issuepermanentline',
            name='destination_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
