# Generated by Django 4.2 on 2025-11-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_receiptpermanent_options_and_more'),
        ('production', '0005_person_processstep_machine_code_personassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_approved', to='production.person'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='production.person'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_approved', to='production.person'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_to_approve', to='production.person'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_cancelled', to='production.person'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_rejected', to='production.person'),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to='production.person'),
        ),
    ]
