# Generated by Django 4.2 on 2025-11-19 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0022_alter_purchaserequest_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requested_by_code',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='approved_by_code',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='approver_code',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='requester_code',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
