# Generated by Django 4.2 on 2025-11-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_person_from_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepermanent',
            name='warehouse_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_issues', to='inventory.warehouserequest'),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='warehouse_request_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
