# Generated by Django 4.2 on 2025-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_warehouse_request_to_issue_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='secondary_batch_number',
            field=models.CharField(blank=True, help_text='User-defined secondary batch number', max_length=50),
        ),
        migrations.AddField(
            model_name='itemserial',
            name='secondary_serial_code',
            field=models.CharField(blank=True, help_text='User-defined secondary serial number', max_length=50),
        ),
    ]
