# Generated by Django 4.2 on 2025-11-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_bom_remove_dates'),
        ('inventory', '0025_add_secondary_batch_and_serial_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workline',
            name='machines',
            field=models.ManyToManyField(blank=True, help_text='Machines assigned to this work line', related_name='work_lines', to='production.machine'),
        ),
        migrations.AddField(
            model_name='workline',
            name='personnel',
            field=models.ManyToManyField(blank=True, help_text='Personnel assigned to this work line', related_name='work_lines', to='production.person'),
        ),
    ]
