# Generated by Django 4.2 on 2025-11-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_add_personnel_machines_to_workline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workline',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='enabled_by',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='workline',
            name='warehouse',
        ),
    ]
