# Generated by Django 4.2 on 2025-11-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_move_workline_to_production'),
        ('production', '0013_move_workline_to_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueconsumptionline',
            name='work_line',
            field=models.ForeignKey(blank=True, help_text='Work line (optional, only if production module is installed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_issue_lines', to='production.workline'),
        ),
        migrations.DeleteModel(
            name='WorkLine',
        ),
    ]
