# Generated by Django 4.2 on 2025-11-24 00:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_smtpserver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0030_migrate_purchase_request_to_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipttemporary',
            name='entered_quantity',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='entered_unit',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='item',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receipttemporary',
            name='warehouse_code',
        ),
        migrations.CreateModel(
            name='ReceiptTemporaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_price_unit', models.CharField(blank=True, help_text='Unit for entered_unit_price (e.g., BOX, CARTON). If empty, same as entered_unit.', max_length=30)),
                ('line_notes', models.TextField(blank=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.receipttemporary')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Temporary Receipt Line',
                'verbose_name_plural': 'Temporary Receipt Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='receipttemporaryline',
            index=models.Index(fields=['company', 'document'], name='inv_rec_tmp_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='receipttemporaryline',
            index=models.Index(fields=['company', 'item'], name='inv_rec_tmp_line_item_idx'),
        ),
    ]
