# Generated by Django 4.2 on 2025-11-27 22:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def migrate_stocktaking_data_to_lines(apps, schema_editor):
    """Migrate existing StocktakingDeficit and StocktakingSurplus data to Line models."""
    # Access old model state before fields are removed
    StocktakingDeficit = apps.get_model('inventory', 'StocktakingDeficit')
    StocktakingDeficitLine = apps.get_model('inventory', 'StocktakingDeficitLine')
    StocktakingSurplus = apps.get_model('inventory', 'StocktakingSurplus')
    StocktakingSurplusLine = apps.get_model('inventory', 'StocktakingSurplusLine')
    
    # Migrate StocktakingDeficit
    for deficit in StocktakingDeficit.objects.all():
        # Check if old fields exist (they should at this point in migration)
        # Use raw SQL to access fields that will be removed
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT item_id, item_code, warehouse_id, warehouse_code, unit,
                       quantity_expected, quantity_counted, quantity_adjusted,
                       valuation_method, unit_cost, total_cost, reason_code,
                       investigation_reference, adjustment_metadata
                FROM inventory_stocktakingdeficit
                WHERE id = %s
            """, [deficit.id])
            row = cursor.fetchone()
            if row and row[0]:  # item_id exists
                StocktakingDeficitLine.objects.create(
                    document=deficit,
                    company=deficit.company,
                    item_id=row[0],
                    item_code=row[1] or '',
                    warehouse_id=row[2],
                    warehouse_code=row[3] or '',
                    unit=row[4] or 'EA',
                    quantity_expected=row[5] or Decimal('0'),
                    quantity_counted=row[6] or Decimal('0'),
                    quantity_adjusted=row[7] or Decimal('0'),
                    valuation_method=row[8] or '',
                    unit_cost=row[9],
                    total_cost=row[10],
                    reason_code=row[11] or '',
                    investigation_reference=row[12] or '',
                    adjustment_metadata=row[13] or {},
                    sort_order=0,
                    created_by=deficit.created_by,
                    is_enabled=deficit.is_enabled,
                )
    
    # Migrate StocktakingSurplus
    for surplus in StocktakingSurplus.objects.all():
        # Use raw SQL to access fields that will be removed
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT item_id, item_code, warehouse_id, warehouse_code, unit,
                       quantity_expected, quantity_counted, quantity_adjusted,
                       valuation_method, unit_cost, total_cost, reason_code,
                       investigation_reference, adjustment_metadata
                FROM inventory_stocktakingsurplus
                WHERE id = %s
            """, [surplus.id])
            row = cursor.fetchone()
            if row and row[0]:  # item_id exists
                StocktakingSurplusLine.objects.create(
                    document=surplus,
                    company=surplus.company,
                    item_id=row[0],
                    item_code=row[1] or '',
                    warehouse_id=row[2],
                    warehouse_code=row[3] or '',
                    unit=row[4] or 'EA',
                    quantity_expected=row[5] or Decimal('0'),
                    quantity_counted=row[6] or Decimal('0'),
                    quantity_adjusted=row[7] or Decimal('0'),
                    valuation_method=row[8] or '',
                    unit_cost=row[9],
                    total_cost=row[10],
                    reason_code=row[11] or '',
                    investigation_reference=row[12] or '',
                    adjustment_metadata=row[13] or {},
                    sort_order=0,
                    created_by=surplus.created_by,
                    is_enabled=surplus.is_enabled,
                )


def reverse_migrate_stocktaking_data(apps, schema_editor):
    """Reverse migration - not implemented as data loss would occur."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0012_populate_section_and_action_registry'),
        ('inventory', '0033_add_warehouse_request_line'),
    ]

    operations = [
        # First, create the Line models
        migrations.CreateModel(
            name='StocktakingSurplusLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Item Code')),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Warehouse Code')),
                ('unit', models.CharField(max_length=30, verbose_name='Unit')),
                ('quantity_expected', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Expected')),
                ('quantity_counted', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Counted')),
                ('quantity_adjusted', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Adjusted')),
                ('valuation_method', models.CharField(blank=True, max_length=30, verbose_name='Valuation Method')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Cost')),
                ('reason_code', models.CharField(blank=True, max_length=30, verbose_name='Reason Code')),
                ('investigation_reference', models.CharField(blank=True, max_length=30, verbose_name='Investigation Reference')),
                ('adjustment_metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktakingsurplus')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktaking_surplus_lines', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktaking_surplus_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stocktaking Surplus Line',
                'verbose_name_plural': 'Stocktaking Surplus Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StocktakingDeficitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Item Code')),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Warehouse Code')),
                ('unit', models.CharField(max_length=30, verbose_name='Unit')),
                ('quantity_expected', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Expected')),
                ('quantity_counted', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Counted')),
                ('quantity_adjusted', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity Adjusted')),
                ('valuation_method', models.CharField(blank=True, max_length=30, verbose_name='Valuation Method')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Cost')),
                ('reason_code', models.CharField(blank=True, max_length=30, verbose_name='Reason Code')),
                ('investigation_reference', models.CharField(blank=True, max_length=30, verbose_name='Investigation Reference')),
                ('adjustment_metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktakingdeficit')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktaking_deficit_lines', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktaking_deficit_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stocktaking Deficit Line',
                'verbose_name_plural': 'Stocktaking Deficit Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='stocktakingsurplusline',
            index=models.Index(fields=['company', 'document'], name='inv_sts_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakingsurplusline',
            index=models.Index(fields=['company', 'item'], name='inv_sts_line_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakingdeficitline',
            index=models.Index(fields=['company', 'document'], name='inv_std_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakingdeficitline',
            index=models.Index(fields=['company', 'item'], name='inv_std_line_item_idx'),
        ),
        # Migrate data before removing fields
        migrations.RunPython(migrate_stocktaking_data_to_lines, reverse_migrate_stocktaking_data),
        # Now remove fields from header models
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='adjustment_metadata',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='investigation_reference',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='quantity_adjusted',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='quantity_counted',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='quantity_expected',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='reason_code',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='valuation_method',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stocktakingdeficit',
            name='warehouse_code',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='adjustment_metadata',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='investigation_reference',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='quantity_adjusted',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='quantity_counted',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='quantity_expected',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='reason_code',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='valuation_method',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stocktakingsurplus',
            name='warehouse_code',
        ),
        migrations.AddField(
            model_name='stocktakingdeficit',
            name='document_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stocktakingsurplus',
            name='document_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='receipttemporary',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Awaiting inspection'), (2, 'Closed/Cancelled'), (3, 'QC Approved')], default=0),
        ),
    ]
