# Generated by Django 4.2 on 2025-11-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_add_stocktaking_line_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueconsumptionline',
            name='cost_center_code',
        ),
        migrations.RemoveField(
            model_name='issueconsumptionline',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='issueconsumptionline',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptconsignmentline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receiptconsignmentline',
            name='entered_price_unit',
        ),
        migrations.RemoveField(
            model_name='receiptconsignmentline',
            name='entered_unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptconsignmentline',
            name='unit_price_estimate',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='entered_price_unit',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='entered_unit_price',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='receiptpermanentline',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='receipttemporaryline',
            name='entered_price_unit',
        ),
        migrations.RemoveField(
            model_name='receipttemporaryline',
            name='entered_unit_price',
        ),
    ]
