# Generated by Django 4.2 on 2025-11-28 11:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_price_fields_from_receipts_and_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemporaryline',
            name='is_qc_approved',
            field=models.PositiveSmallIntegerField(default=0, help_text='Whether this line is approved by QC'),
        ),
        migrations.AddField(
            model_name='receipttemporaryline',
            name='qc_approval_notes',
            field=models.TextField(blank=True, help_text='QC approval notes for this line'),
        ),
        migrations.AddField(
            model_name='receipttemporaryline',
            name='qc_approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Quantity approved by QC (can be less than original quantity)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
