# Generated by Django 4.2 on 2025-11-28 11:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_add_qc_approval_fields_to_receipt_temporary_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemporaryline',
            name='is_qc_rejected',
            field=models.PositiveSmallIntegerField(default=0, help_text='Whether this line is rejected by QC'),
        ),
        migrations.AddField(
            model_name='receipttemporaryline',
            name='qc_rejected_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Quantity rejected by QC', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='receipttemporaryline',
            name='qc_rejection_reason',
            field=models.TextField(blank=True, help_text='QC rejection reason for this line'),
        ),
    ]
