# Generated by Django 4.2 on 2025-11-28 12:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0013_add_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0037_add_qc_rejection_fields_to_receipt_temporary_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCRejectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Quantity rejected for this specific reason', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Rejected Quantity')),
                ('reason', models.TextField(help_text='Detailed reason for rejecting this quantity', verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_rejection_details', to='shared.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_rejection_details_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_details', to='inventory.receipttemporaryline', verbose_name='Receipt Line')),
            ],
            options={
                'verbose_name': 'QC Rejection Detail',
                'verbose_name_plural': 'QC Rejection Details',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='qcrejectiondetail',
            index=models.Index(fields=['company', 'line'], name='qc_rej_detail_line_idx'),
        ),
    ]
