# Generated by Django 4.2 on 2025-11-30 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_issueconsignment_editing_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemporaryline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_receipt_lines', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='receipttemporaryline',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
    ]
