# Generated by Django 4.2 on 2025-12-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_fiscal_year_to_documents'),
        ('inventory', '0040_add_supplier_to_receipt_temporary_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueconsignment',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='issueconsumption',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='issuepermanent',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='receiptconsignment',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='receiptpermanent',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='receipttemporary',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='stocktakingdeficit',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='stocktakingrecord',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='stocktakingsurplus',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='warehouserequest',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear'),
        ),
    ]
