# Generated by Django 4.2 on 2025-12-03 07:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0010_add_warehouse_transfer_issue'),
        ('shared', '0014_add_editable_model_fields'),
        ('inventory', '0041_add_fiscal_year_to_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueWarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('notes', models.TextField(blank=True)),
                ('document_code', models.CharField(max_length=20, unique=True)),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Transfer Issue',
                'verbose_name_plural': 'Warehouse Transfer Issues',
                'ordering': ('-document_date', 'document_code'),
            },
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='request_code',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='IssueWarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('unit', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('entered_unit', models.CharField(blank=True, max_length=30)),
                ('entered_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True)),
                ('source_warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('destination_warehouse_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_destination_lines', to='inventory.warehouse')),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issuewarehousetransfer')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.item')),
                ('serials', models.ManyToManyField(blank=True, related_name='issue_warehouse_transfer_lines', to='inventory.itemserial')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_source_lines', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Transfer Issue Line',
                'verbose_name_plural': 'Warehouse Transfer Issue Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='issuewarehousetransferline',
            index=models.Index(fields=['company', 'document'], name='inv_issue_wht_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='issuewarehousetransferline',
            index=models.Index(fields=['company', 'item'], name='inv_issue_wht_line_item_idx'),
        ),
    ]
