# Generated by Django 4.2 on 2025-12-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_change_destination_work_center_to_workline'),
        ('inventory', '0042_add_warehouse_transfer_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuewarehousetransfer',
            name='production_transfer',
            field=models.ForeignKey(blank=True, help_text='The production transfer request that created this warehouse transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to='production.transfertoline', verbose_name='Production Transfer'),
        ),
        migrations.AddField(
            model_name='issuewarehousetransfer',
            name='production_transfer_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
