# Generated by Django 4.2 on 2025-12-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_add_approver_to_warehouse_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='batch_number',
        ),
    ]
