# Generated by Django 4.2 on 2026-01-04 14:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0006_create_item_batch'),
        ('inventory', '0047_remove_batch_number_from_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('batch_number', models.CharField(help_text='Cached batch number', max_length=30, verbose_name='Batch Number')),
                ('warehouse_code', models.CharField(help_text='Cached warehouse code', max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')], verbose_name='Warehouse Code')),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Current quantity of this batch in this warehouse', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantity')),
                ('unit', models.CharField(help_text='Unit of measure', max_length=30, verbose_name='Unit')),
                ('batch', models.ForeignKey(help_text='Batch reference from QC module', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='qc.itembatch', verbose_name='Batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_inventory', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Batch Warehouse Inventory',
                'verbose_name_plural': 'Batch Warehouse Inventories',
                'ordering': ('company', 'batch', 'warehouse'),
            },
        ),
        migrations.AddIndex(
            model_name='batchwarehouse',
            index=models.Index(fields=['company', 'batch'], name='inv_batch_wh_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='batchwarehouse',
            index=models.Index(fields=['company', 'warehouse'], name='inv_batch_wh_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='batchwarehouse',
            index=models.Index(fields=['company', 'batch_number'], name='inv_batch_wh_batch_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchwarehouse',
            constraint=models.UniqueConstraint(fields=('company', 'batch', 'warehouse'), name='inventory_batch_warehouse_unique'),
        ),
    ]
