# Generated by Django 4.2 on 2026-01-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_create_item_batch'),
        ('inventory', '0048_create_batch_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueconsignmentline',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch to issue from - required for batch-tracked items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='qc.itembatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='issueconsignmentline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Cached batch number', max_length=30, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='issueconsumptionline',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch to issue from - required for batch-tracked items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='qc.itembatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='issueconsumptionline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Cached batch number', max_length=30, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='issuepermanentline',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch to issue from - required for batch-tracked items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='qc.itembatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='issuepermanentline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Cached batch number', max_length=30, verbose_name='Batch Number'),
        ),
        migrations.AddField(
            model_name='issuewarehousetransferline',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch to issue from - required for batch-tracked items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='qc.itembatch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='issuewarehousetransferline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Cached batch number', max_length=30, verbose_name='Batch Number'),
        ),
    ]
