# Generated by Django 4.2 on 2026-01-04 15:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        ('qc', '0006_create_item_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0049_add_batch_to_issue_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueconsignmentline',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='issueconsignmentline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='issueconsumptionline',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='issueconsumptionline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='issuepermanentline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='issuewarehousetransferline',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='issuewarehousetransferline',
            name='batch_number',
        ),
        migrations.CreateModel(
            name='IssueBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('issue_line_type', models.CharField(max_length=50, verbose_name='Issue Line Type')),
                ('issue_line_id', models.BigIntegerField(verbose_name='Issue Line ID')),
                ('batch_number', models.CharField(help_text='Cached batch number', max_length=30, verbose_name='Batch Number')),
                ('allocated_quantity', models.DecimalField(decimal_places=6, help_text='Quantity allocated from this batch to the issue line', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Allocated Quantity')),
                ('unit', models.CharField(help_text='Unit of measure', max_length=30, verbose_name='Unit')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_allocations', to='qc.itembatch', verbose_name='Batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Batch Allocation',
                'verbose_name_plural': 'Issue Batch Allocations',
                'ordering': ('company', 'issue_line_type', 'issue_line_id', 'batch'),
            },
        ),
        migrations.AddIndex(
            model_name='issuebatchallocation',
            index=models.Index(fields=['company', 'issue_line_id'], name='inv_batch_alloc_line_idx'),
        ),
        migrations.AddIndex(
            model_name='issuebatchallocation',
            index=models.Index(fields=['company', 'batch'], name='inv_batch_alloc_batch_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuebatchallocation',
            constraint=models.UniqueConstraint(fields=('company', 'issue_line_type', 'issue_line_id', 'batch'), name='inventory_issue_batch_allocation_unique'),
        ),
    ]
