# Generated by Django 4.2 on 2026-01-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_create_issue_batch_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemserial',
            name='receipt_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.receiptpermanent'),
        ),
    ]
