# Generated by Django 4.2 on 2025-11-09 10:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('temporary_receipt_code', models.CharField(max_length=20)),
                ('inspection_code', models.CharField(max_length=30, unique=True)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('inspection_status', models.CharField(choices=[('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('rework', 'Rework'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('inspector_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('inspection_summary', models.TextField(blank=True)),
                ('inspection_results', models.JSONField(blank=True, default=dict)),
                ('nonconformity_flag', models.PositiveSmallIntegerField(default=0)),
                ('nonconformity_report_id', models.BigIntegerField(blank=True, null=True)),
                ('approval_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_with_deviation', 'Approved with Deviation'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_inspections_approved', to='shared.person')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_inspections', to='shared.person')),
                ('temporary_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspection', to='inventory.receipttemporary')),
            ],
            options={
                'verbose_name': 'Receipt Inspection',
                'verbose_name_plural': 'Receipt Inspections',
                'ordering': ('-inspection_date', 'inspection_code'),
            },
        ),
        migrations.AddConstraint(
            model_name='receiptinspection',
            constraint=models.UniqueConstraint(fields=('company', 'temporary_receipt'), name='qc_inspection_unique_temp_receipt'),
        ),
    ]
