# Generated by Django 4.2 on 2025-11-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptinspection',
            name='activated_at',
        ),
        migrations.RemoveField(
            model_name='receiptinspection',
            name='deactivated_at',
        ),
    ]
