# Generated by Django 4.2 on 2025-11-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_person_processstep_machine_code_personassignment_and_more'),
        ('qc', '0003_remove_receiptinspection_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptinspection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_inspections_approved', to='production.person'),
        ),
        migrations.AlterField(
            model_name='receiptinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_inspections', to='production.person'),
        ),
    ]
