# Generated by Django 4.2 on 2025-11-21 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0004_alter_receiptinspection_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptinspection',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_inspections_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
