# Generated by Django 4.2 on 2025-12-30 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        ('inventory', '0047_remove_batch_number_from_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0005_change_receipt_inspection_approved_by_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(help_text='Cached item code', max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('batch_number', models.CharField(help_text='Batch number for this receipt line', max_length=30)),
                ('receipt_temporary_code', models.CharField(help_text='Cached temporary receipt document code', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Quantity for this batch', max_digits=18)),
                ('unit', models.CharField(help_text='Unit of measure', max_length=30)),
                ('warehouse_code', models.CharField(blank=True, help_text='Cached warehouse code', max_length=6, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed'), ('scrapped', 'Scrapped')], default='available', help_text='Current status of the batch', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_batches', to='inventory.item')),
                ('receipt_temporary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.receipttemporary')),
                ('receipt_temporary_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.receipttemporaryline')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_batches', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Item Batch',
                'verbose_name_plural': 'Item Batches',
                'ordering': ('company', 'item', 'batch_number', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['company', 'item'], name='qc_batch_item_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['company', 'receipt_temporary'], name='qc_batch_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['company', 'receipt_temporary_line'], name='qc_batch_line_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['company', 'batch_number'], name='qc_batch_number_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['company', 'status'], name='qc_batch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='itembatch',
            constraint=models.UniqueConstraint(fields=('company', 'batch_number'), name='qc_batch_unique_number'),
        ),
    ]
