"""
Centralised permission definitions for the application.

These structures will be consumed by the upcoming access level / role engine.
Until persistence is implemented, this module documents the expected actions
per feature and can be reused in fixtures, forms or serializers later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, unique
from typing import Dict, List

from django.utils.translation import gettext_lazy as _


@unique
class PermissionAction(Enum):
    """
    Supported primitive actions that can be attached to an access level.
    """

    VIEW_OWN = "view_own"
    VIEW_ALL = "view_all"
    VIEW_SAME_GROUP = "view_same_group"
    CREATE = "create"
    EDIT_OWN = "edit_own"
    EDIT_OTHER = "edit_other"
    EDIT_SAME_GROUP = "edit_same_group"
    DELETE_OWN = "delete_own"
    DELETE_OTHER = "delete_other"
    DELETE_SAME_GROUP = "delete_same_group"
    LOCK_OWN = "lock_own"
    LOCK_OTHER = "lock_other"
    LOCK_SAME_GROUP = "lock_same_group"
    UNLOCK_OWN = "unlock_own"
    UNLOCK_OTHER = "unlock_other"
    UNLOCK_SAME_GROUP = "unlock_same_group"
    APPROVE = "approve"
    REJECT = "reject"
    CANCEL = "cancel"
    CREATE_TRANSFER_FROM_ORDER = "create_transfer_from_order"
    CREATE_RECEIPT = "create_receipt"
    CREATE_RECEIPT_FROM_PURCHASE_REQUEST = "create_receipt_from_purchase_request"
    CREATE_ISSUE_FROM_WAREHOUSE_REQUEST = "create_issue_from_warehouse_request"


@dataclass(frozen=True)
class FeaturePermission:
    """
    Describes a navigational feature together with the actions it supports.
    """

    code: str
    label: str
    actions: List[PermissionAction] = field(default_factory=list)


FEATURE_PERMISSION_MAP: Dict[str, FeaturePermission] = {
    # Shared – Company & User Management
    "shared.companies": FeaturePermission(
        code="shared.companies",
        label=_("Companies"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "shared.company_units": FeaturePermission(
        code="shared.company_units",
        label=_("Company Units"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "shared.smtp_servers": FeaturePermission(
        code="shared.smtp_servers",
        label=_("SMTP Servers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "production.personnel": FeaturePermission(
        code="production.personnel",
        label=_("Personnel"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "production.machines": FeaturePermission(
        code="production.machines",
        label=_("Machines"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "production.bom": FeaturePermission(
        code="production.bom",
        label=_("BOM (Bill of Materials)"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "production.processes": FeaturePermission(
        code="production.processes",
        label=_("Processes"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
        ],
    ),
    "production.product_orders": FeaturePermission(
        code="production.product_orders",
        label=_("Product Orders"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.CREATE_TRANSFER_FROM_ORDER,
        ],
    ),
    "production.transfer_requests": FeaturePermission(
        code="production.transfer_requests",
        label=_("Transfer to Line Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "production.transfer_requests.qc_approval": FeaturePermission(
        code="production.transfer_requests.qc_approval",
        label=_("QC Approval for Transfer to Line Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "production.performance_records": FeaturePermission(
        code="production.performance_records",
        label=_("Performance Records"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_OTHER,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CREATE_RECEIPT,
        ],
    ),
    "production.tracking_identification": FeaturePermission(
        code="production.tracking_identification",
        label=_("Tracking and Identification"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "production.qc_operations": FeaturePermission(
        code="production.qc_operations",
        label=_("QC Operations"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "production.rework": FeaturePermission(
        code="production.rework",
        label=_("Rework Documents"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_OTHER,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "shared.users": FeaturePermission(
        code="shared.users",
        label=_("Users"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "shared.groups": FeaturePermission(
        code="shared.groups",
        label=_("Groups"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "shared.access_levels": FeaturePermission(
        code="shared.access_levels",
        label=_("Access Levels"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
        ],
    ),
    # Inventory – Master Data
    "inventory.master.item_types": FeaturePermission(
        code="inventory.master.item_types",
        label=_("Item Types"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "inventory.master.item_categories": FeaturePermission(
        code="inventory.master.item_categories",
        label=_("Item Categories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "inventory.master.item_subcategories": FeaturePermission(
        code="inventory.master.item_subcategories",
        label=_("Item Subcategories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "inventory.master.items": FeaturePermission(
        code="inventory.master.items",
        label=_("Items"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "inventory.master.item_serials": FeaturePermission(
        code="inventory.master.item_serials",
        label=_("Item Serials"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "inventory.master.warehouses": FeaturePermission(
        code="inventory.master.warehouses",
        label=_("Warehouses"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "production.work_lines": FeaturePermission(
        code="production.work_lines",
        label=_("Work Lines"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Inventory – Suppliers
    "inventory.suppliers.categories": FeaturePermission(
        code="inventory.suppliers.categories",
        label=_("Supplier Categories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "inventory.suppliers.list": FeaturePermission(
        code="inventory.suppliers.list",
        label=_("Suppliers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Inventory – Receipts
    "inventory.receipts.temporary": FeaturePermission(
        code="inventory.receipts.temporary",
        label=_("Temporary Receipts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_RECEIPT_FROM_PURCHASE_REQUEST,
        ],
    ),
    "inventory.receipts.permanent": FeaturePermission(
        code="inventory.receipts.permanent",
        label=_("Permanent Receipts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_RECEIPT_FROM_PURCHASE_REQUEST,
        ],
    ),
    "inventory.receipts.consignment": FeaturePermission(
        code="inventory.receipts.consignment",
        label=_("Consignment Receipts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_RECEIPT_FROM_PURCHASE_REQUEST,
        ],
    ),
    # Inventory – Issues
    "inventory.issues.permanent": FeaturePermission(
        code="inventory.issues.permanent",
        label=_("Permanent Issues"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_ISSUE_FROM_WAREHOUSE_REQUEST,
        ],
    ),
    "inventory.issues.consumption": FeaturePermission(
        code="inventory.issues.consumption",
        label=_("Consumption Issues"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_ISSUE_FROM_WAREHOUSE_REQUEST,
        ],
    ),
    "inventory.issues.consignment": FeaturePermission(
        code="inventory.issues.consignment",
        label=_("Consignment Issues"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_ISSUE_FROM_WAREHOUSE_REQUEST,
        ],
    ),
    # Inventory – Requests
    "inventory.requests.purchase": FeaturePermission(
        code="inventory.requests.purchase",
        label=_("Purchase Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_RECEIPT_FROM_PURCHASE_REQUEST,
        ],
    ),
    "inventory.requests.warehouse": FeaturePermission(
        code="inventory.requests.warehouse",
        label=_("Warehouse Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
            PermissionAction.CREATE_ISSUE_FROM_WAREHOUSE_REQUEST,
        ],
    ),
    # Inventory – Stocktaking & Balance
    "inventory.stocktaking.deficit": FeaturePermission(
        code="inventory.stocktaking.deficit",
        label=_("Stocktaking Deficit"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
        ],
    ),
    "inventory.stocktaking.surplus": FeaturePermission(
        code="inventory.stocktaking.surplus",
        label=_("Stocktaking Surplus"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
        ],
    ),
    "inventory.stocktaking.records": FeaturePermission(
        code="inventory.stocktaking.records",
        label=_("Stocktaking Records"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_OTHER,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
            PermissionAction.APPROVE,
        ],
    ),
    "inventory.balance": FeaturePermission(
        code="inventory.balance",
        label=_("Inventory Balance"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # QC – Inspections
    "qc.inspections": FeaturePermission(
        code="qc.inspections",
        label=_("QC Inspections"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
            PermissionAction.CANCEL,
        ],
    ),
    # Accounting – Dashboard
    "accounting.dashboard": FeaturePermission(
        code="accounting.dashboard",
        label=_("Accounting Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Accounting – Fiscal Years
    "accounting.fiscal_years": FeaturePermission(
        code="accounting.fiscal_years",
        label=_("Fiscal Years"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Accounting – Chart of Accounts
    "accounting.accounts": FeaturePermission(
        code="accounting.accounts",
        label=_("Chart of Accounts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.accounts.gl": FeaturePermission(
        code="accounting.accounts.gl",
        label=_("GL Accounts (حساب کل)"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.accounts.sub": FeaturePermission(
        code="accounting.accounts.sub",
        label=_("Sub Accounts (حساب معین)"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.accounts.tafsili": FeaturePermission(
        code="accounting.accounts.tafsili",
        label=_("Tafsili Accounts (حساب تفصیلی)"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.accounts.tafsili_hierarchy": FeaturePermission(
        code="accounting.accounts.tafsili_hierarchy",
        label=_("Tafsili Hierarchy (تفصیلی چند سطحی)"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.attachments.upload": FeaturePermission(
        code="accounting.attachments.upload",
        label=_("Document Attachments Upload"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
        ],
    ),
    "accounting.attachments.list": FeaturePermission(
        code="accounting.attachments.list",
        label=_("Document Attachments List"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.attachments.download": FeaturePermission(
        code="accounting.attachments.download",
        label=_("Document Attachments Download"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.attachments.attach_to_document": FeaturePermission(
        code="accounting.attachments.attach_to_document",
        label=_("Attach File to Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
        ],
    ),
    # Accounting – General
    "accounting.general.ledger": FeaturePermission(
        code="accounting.general.ledger",
        label=_("General Ledger"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.general.subsidiary": FeaturePermission(
        code="accounting.general.subsidiary",
        label=_("Subsidiary Ledgers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.general.detail": FeaturePermission(
        code="accounting.general.detail",
        label=_("Detail Ledgers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Accounting – Documents
    "accounting.documents.entry": FeaturePermission(
        code="accounting.documents.entry",
        label=_("Entry Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
        ],
    ),
    "accounting.documents.exit": FeaturePermission(
        code="accounting.documents.exit",
        label=_("Exit Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.LOCK_OWN,
            PermissionAction.LOCK_OTHER,
            PermissionAction.LOCK_SAME_GROUP,
            PermissionAction.UNLOCK_OWN,
            PermissionAction.UNLOCK_OTHER,
            PermissionAction.UNLOCK_SAME_GROUP,
        ],
    ),
    "accounting.documents.create": FeaturePermission(
        code="accounting.documents.create",
        label=_("Create Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
        ],
    ),
    "accounting.documents.list": FeaturePermission(
        code="accounting.documents.list",
        label=_("Documents List"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.documents.status": FeaturePermission(
        code="accounting.documents.status",
        label=_("Document Status"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.documents.tafsili_movements": FeaturePermission(
        code="accounting.documents.tafsili_movements",
        label=_("Tafsili Movements"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Accounting – Income/Expense
    "accounting.income_expense.categories": FeaturePermission(
        code="accounting.income_expense.categories",
        label=_("Income/Expense Categories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.cost_allocation": FeaturePermission(
        code="accounting.income_expense.cost_allocation",
        label=_("Cost Allocation"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.cost_center_report": FeaturePermission(
        code="accounting.income_expense.cost_center_report",
        label=_("Cost Center Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.cost_centers": FeaturePermission(
        code="accounting.income_expense.cost_centers",
        label=_("Cost Centers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.expense": FeaturePermission(
        code="accounting.income_expense.expense",
        label=_("Expense Management"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.expense_report": FeaturePermission(
        code="accounting.income_expense.expense_report",
        label=_("Expense Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.income": FeaturePermission(
        code="accounting.income_expense.income",
        label=_("Income Management"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.income_expense.income_report": FeaturePermission(
        code="accounting.income_expense.income_report",
        label=_("Income Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Accounting – Parties
    "accounting.parties.accounts": FeaturePermission(
        code="accounting.parties.accounts",
        label=_("Party Accounts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.parties.balance_report": FeaturePermission(
        code="accounting.parties.balance_report",
        label=_("Party Balance Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.parties.list": FeaturePermission(
        code="accounting.parties.list",
        label=_("Parties List"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.parties.movements": FeaturePermission(
        code="accounting.parties.movements",
        label=_("Party Movements"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.parties.transactions": FeaturePermission(
        code="accounting.parties.transactions",
        label=_("Party Transactions"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Accounting – Reports
    "accounting.reports.account_movements": FeaturePermission(
        code="accounting.reports.account_movements",
        label=_("Account Movements Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.balance_sheet": FeaturePermission(
        code="accounting.reports.balance_sheet",
        label=_("Balance Sheet Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.cash_flow": FeaturePermission(
        code="accounting.reports.cash_flow",
        label=_("Cash Flow Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.check_report": FeaturePermission(
        code="accounting.reports.check_report",
        label=_("Check Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.income_statement": FeaturePermission(
        code="accounting.reports.income_statement",
        label=_("Income Statement Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.monthly": FeaturePermission(
        code="accounting.reports.monthly",
        label=_("Monthly Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.party_statement": FeaturePermission(
        code="accounting.reports.party_statement",
        label=_("Party Statement Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.tafsili_cost_center": FeaturePermission(
        code="accounting.reports.tafsili_cost_center",
        label=_("Tafsili Cost Center Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.treasury_report": FeaturePermission(
        code="accounting.reports.treasury_report",
        label=_("Treasury Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.trial_balance": FeaturePermission(
        code="accounting.reports.trial_balance",
        label=_("Trial Balance Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.reports.vat": FeaturePermission(
        code="accounting.reports.vat",
        label=_("VAT Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Accounting – Settings
    "accounting.settings": FeaturePermission(
        code="accounting.settings",
        label=_("Accounting Settings"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.settings.tax": FeaturePermission(
        code="accounting.settings.tax",
        label=_("Tax Settings"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.settings.treasury": FeaturePermission(
        code="accounting.settings.treasury",
        label=_("Treasury Settings"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    # Accounting – Tax
    "accounting.tax.discrepancy_report": FeaturePermission(
        code="accounting.tax.discrepancy_report",
        label=_("Tax Discrepancy Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.tax.seasonal": FeaturePermission(
        code="accounting.tax.seasonal",
        label=_("Seasonal Tax"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.tax.ttms": FeaturePermission(
        code="accounting.tax.ttms",
        label=_("TTMS Tax"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.tax.validation": FeaturePermission(
        code="accounting.tax.validation",
        label=_("Tax Validation"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.tax.vat": FeaturePermission(
        code="accounting.tax.vat",
        label=_("VAT Tax"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Accounting – Treasury
    "accounting.treasury.expense": FeaturePermission(
        code="accounting.treasury.expense",
        label=_("Expense Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "accounting.treasury.income": FeaturePermission(
        code="accounting.treasury.income",
        label=_("Income Document"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "accounting.treasury.accounts": FeaturePermission(
        code="accounting.treasury.accounts",
        label=_("Treasury Accounts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.treasury.cash_report": FeaturePermission(
        code="accounting.treasury.cash_report",
        label=_("Cash Report"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "accounting.treasury.checks": FeaturePermission(
        code="accounting.treasury.checks",
        label=_("Checks Management"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "accounting.treasury.pay": FeaturePermission(
        code="accounting.treasury.pay",
        label=_("Pay Transactions"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.treasury.receive": FeaturePermission(
        code="accounting.treasury.receive",
        label=_("Receive Transactions"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.treasury.reconciliation": FeaturePermission(
        code="accounting.treasury.reconciliation",
        label=_("Bank Reconciliation"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.treasury.transactions": FeaturePermission(
        code="accounting.treasury.transactions",
        label=_("Treasury Transactions"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.treasury.transfer": FeaturePermission(
        code="accounting.treasury.transfer",
        label=_("Transfer Transactions"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Accounting – Utils
    "accounting.utils.backup": FeaturePermission(
        code="accounting.utils.backup",
        label=_("Backup"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
        ],
    ),
    "accounting.utils.close_temp": FeaturePermission(
        code="accounting.utils.close_temp",
        label=_("Close Temporary Accounts"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.utils.closing": FeaturePermission(
        code="accounting.utils.closing",
        label=_("Period Closing"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.utils.integration": FeaturePermission(
        code="accounting.utils.integration",
        label=_("Integration"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "accounting.utils.opening": FeaturePermission(
        code="accounting.utils.opening",
        label=_("Period Opening"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    # Accounting – Payroll
    "accounting.payroll.payment": FeaturePermission(
        code="accounting.payroll.payment",
        label=_("Payroll Payment"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.payroll.insurance_tax": FeaturePermission(
        code="accounting.payroll.insurance_tax",
        label=_("Insurance and Tax Settings"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "accounting.payroll.document": FeaturePermission(
        code="accounting.payroll.document",
        label=_("Payroll Document Upload"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "accounting.payroll.bank_transfer": FeaturePermission(
        code="accounting.payroll.bank_transfer",
        label=_("Bank Transfer Output"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Sales
    "sales.dashboard": FeaturePermission(
        code="sales.dashboard",
        label=_("Sales Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    "sales.invoice": FeaturePermission(
        code="sales.invoice",
        label=_("Sales Invoice"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    # HR – Dashboard
    "hr.dashboard": FeaturePermission(
        code="hr.dashboard",
        label=_("HR Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # HR – Personnel
    "hr.personnel": FeaturePermission(
        code="hr.personnel",
        label=_("Personnel"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.personnel.decree": FeaturePermission(
        code="hr.personnel.decree",
        label=_("Personnel Decree Assignment"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_OTHER,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "hr.personnel.form": FeaturePermission(
        code="hr.personnel.form",
        label=_("Personnel Forms"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.personnel.form_groups": FeaturePermission(
        code="hr.personnel.form_groups",
        label=_("Personnel Form Groups"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.personnel.form_subgroups": FeaturePermission(
        code="hr.personnel.form_subgroups",
        label=_("Personnel Form Sub-Groups"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # HR - Payroll Decrees
    "hr.payroll.decrees": FeaturePermission(
        code="hr.payroll.decrees",
        label=_("Payroll Decrees"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.payroll.decree_groups": FeaturePermission(
        code="hr.payroll.decree_groups",
        label=_("Decree Groups"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.payroll.decree_subgroups": FeaturePermission(
        code="hr.payroll.decree_subgroups",
        label=_("Decree Sub-Groups"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # HR – Requests
    "hr.requests.leave": FeaturePermission(
        code="hr.requests.leave",
        label=_("Leave Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "hr.requests.sick_leave": FeaturePermission(
        code="hr.requests.sick_leave",
        label=_("Sick Leave Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "hr.requests.loan": FeaturePermission(
        code="hr.requests.loan",
        label=_("Loan Requests"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    # HR – Loans
    "hr.loans.management": FeaturePermission(
        code="hr.loans.management",
        label=_("Loan Management"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "hr.loans.scheduling": FeaturePermission(
        code="hr.loans.scheduling",
        label=_("Loan Scheduling"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "hr.loans.savings_fund": FeaturePermission(
        code="hr.loans.savings_fund",
        label=_("Savings Fund"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Office Automation – Dashboard
    "office_automation.dashboard": FeaturePermission(
        code="office_automation.dashboard",
        label=_("Office Automation Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Office Automation – Inbox
    "office_automation.inbox.incoming": FeaturePermission(
        code="office_automation.inbox.incoming",
        label=_("Incoming Letters"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    "office_automation.inbox.write": FeaturePermission(
        code="office_automation.inbox.write",
        label=_("Write Letter"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    "office_automation.inbox.fill_form": FeaturePermission(
        code="office_automation.inbox.fill_form",
        label=_("Fill Form"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
        ],
    ),
    # Office Automation – Processes
    "office_automation.processes.engine": FeaturePermission(
        code="office_automation.processes.engine",
        label=_("Process Engine"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "office_automation.processes.form_connection": FeaturePermission(
        code="office_automation.processes.form_connection",
        label=_("Process-Form Connection"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Office Automation – Forms
    "office_automation.forms.builder": FeaturePermission(
        code="office_automation.forms.builder",
        label=_("Form Builder"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Transportation
    "transportation.dashboard": FeaturePermission(
        code="transportation.dashboard",
        label=_("Transportation Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Procurement – Dashboard
    "procurement.dashboard": FeaturePermission(
        code="procurement.dashboard",
        label=_("Procurement Dashboard"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
        ],
    ),
    # Procurement – Purchases
    "procurement.purchases": FeaturePermission(
        code="procurement.purchases",
        label=_("Purchases"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
            PermissionAction.APPROVE,
            PermissionAction.REJECT,
        ],
    ),
    # Procurement – Buyers
    "procurement.buyers": FeaturePermission(
        code="procurement.buyers",
        label=_("Buyers"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    # Ticketing – Management
    "ticketing.management.categories": FeaturePermission(
        code="ticketing.management.categories",
        label=_("Ticket Categories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "ticketing.management.subcategories": FeaturePermission(
        code="ticketing.management.subcategories",
        label=_("Ticket Subcategories"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
    "ticketing.management.templates": FeaturePermission(
        code="ticketing.management.templates",
        label=_("Ticket Templates"),
        actions=[
            PermissionAction.VIEW_OWN,
            PermissionAction.VIEW_ALL,
            PermissionAction.VIEW_SAME_GROUP,
            PermissionAction.CREATE,
            PermissionAction.EDIT_OWN,
            PermissionAction.EDIT_SAME_GROUP,
            PermissionAction.DELETE_OWN,
            PermissionAction.DELETE_SAME_GROUP,
        ],
    ),
}


def list_feature_permissions() -> List[FeaturePermission]:
    """
    Convenience helper for iterating over defined permissions (e.g. in forms).
    """

    return list(FEATURE_PERMISSION_MAP.values())

