# Generated by Django 4.2 on 2025-12-01 00:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_add_editable_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('document_code', models.CharField(blank=True, editable=False, max_length=30)),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('document_number', models.CharField(editable=False, help_text='Auto-generated document number', max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('AUTOMATIC', 'Automatic Entry'), ('OPENING', 'Opening Entry'), ('CLOSING', 'Closing Entry'), ('ADJUSTMENT', 'Adjustment')], help_text='Document classification', max_length=30)),
                ('description', models.TextField(help_text='Document description/explanation')),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice number, receipt number, etc.)', max_length=100)),
                ('reference_type', models.CharField(blank=True, help_text="Type of reference (e.g., 'INVENTORY_RECEIPT', 'SALES_INVOICE')", max_length=50)),
                ('reference_id', models.BigIntegerField(blank=True, help_text='Foreign key to referenced document', null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all debit lines', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all credit lines (must equal total_debit)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Document workflow status', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When document was posted', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When document was locked', null=True)),
                ('attachment_count', models.PositiveSmallIntegerField(default=0, help_text='Number of attached files')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(help_text='Fiscal year for document', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.fiscalyear')),
                ('locked_by', models.ForeignKey(blank=True, help_text='User who locked the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_documents_locked', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, help_text='Optional period reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.period')),
                ('posted_by', models.ForeignKey(blank=True, help_text='User who posted the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_documents_posted', to=settings.AUTH_USER_MODEL)),
                ('reversed_document', models.ForeignKey(blank=True, help_text='Reference to reversal document if reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_documents', to='accounting.accountingdocument')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Document',
                'verbose_name_plural': 'Accounting Documents',
                'ordering': ('company', '-document_date', '-document_number'),
            },
        ),
        migrations.CreateModel(
            name='AccountingDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('line_number', models.PositiveSmallIntegerField(help_text='Sequential line number within document')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (must be 0 if credit_amount > 0)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (must be 0 if debit_amount > 0)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, help_text='Line item description')),
                ('party_id', models.BigIntegerField(blank=True, help_text='Optional party reference (will be FK to accounting_party)', null=True)),
                ('cost_center_id', models.BigIntegerField(blank=True, help_text='Optional cost center allocation (will be FK to accounting_cost_center)', null=True)),
                ('project_id', models.BigIntegerField(blank=True, help_text='Optional project reference', null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate percentage if applicable', max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='VAT amount if applicable', max_digits=18, null=True)),
                ('reference', models.CharField(blank=True, help_text='Additional reference for line item', max_length=100)),
                ('account', models.ForeignKey(help_text='Account being debited or credited', on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.accountingdocument')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Document Line',
                'verbose_name_plural': 'Accounting Document Lines',
                'ordering': ('company', 'document', 'line_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='accountingdocumentline',
            constraint=models.UniqueConstraint(fields=('company', 'document', 'line_number'), name='accounting_document_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='accountingdocumentline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), _connector='OR'), name='accounting_document_line_debit_or_credit'),
        ),
        migrations.AddConstraint(
            model_name='accountingdocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='accounting_document_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='accountingdocument',
            constraint=models.CheckConstraint(check=models.Q(('total_debit', models.F('total_credit'))), name='accounting_document_balanced'),
        ),
    ]
