# Generated by Django 4.2 on 2025-12-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingdocument_accountingdocumentline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdocument',
            name='fiscal_year',
            field=models.ForeignKey(help_text='Fiscal year for document (auto-populated from document_date)', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.fiscalyear'),
        ),
    ]
