# Generated by Django 4.2 on 2025-12-01 11:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0014_add_editable_model_fields'),
        ('accounting', '0003_add_fiscal_year_to_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('company', 'account_code'), 'verbose_name': 'حساب', 'verbose_name_plural': 'حساب\u200cها'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.CharField(help_text="کد سلسله مراتبی حساب (مثال: '1.01.001')", max_length=20, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'کل'), (2, 'معین'), (3, 'تفصیلی')], help_text='سطح حساب: 1=کل، 2=معین، 3=تفصیلی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(help_text='نام حساب (فارسی)', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name_en',
            field=models.CharField(blank=True, help_text='نام حساب (انگلیسی)', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'دارایی'), ('LIABILITY', 'بدهی'), ('EQUITY', 'حقوق صاحبان سهام'), ('REVENUE', 'درآمد'), ('EXPENSE', 'هزینه')], help_text='نوع حساب', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='مانده جاری (محاسبه شده)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات حساب و یادداشت\u200cهای استفاده'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_system_account',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='حساب\u200cهای تولید شده توسط سیستم قابل حذف نیستند'),
        ),
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], help_text='طرف تراز مورد انتظار', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مانده ابتدای سال مالی جاری', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='حساب والد برای ساختار سلسله مراتبی', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='TafsiliSubAccountRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('is_primary', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='حساب معین اصلی (برای نمایش پیش\u200cفرض)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('sub_account', models.ForeignKey(help_text='حساب معین', limit_choices_to={'account_level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_account_relations', to='accounting.account')),
                ('tafsili_account', models.ForeignKey(help_text='حساب تفصیلی', limit_choices_to={'account_level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_account_relations_as_tafsili', to='accounting.account')),
            ],
            options={
                'verbose_name': 'رابطه تفصیلی-معین',
                'verbose_name_plural': 'روابط تفصیلی-معین',
                'ordering': ('company', 'tafsili_account', '-is_primary', 'sub_account'),
            },
        ),
        migrations.CreateModel(
            name='SubAccountGLAccountRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('is_primary', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='حساب کل اصلی (برای نمایش پیش\u200cفرض)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(help_text='حساب کل', limit_choices_to={'account_level': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_account_relations_as_gl', to='accounting.account')),
                ('sub_account', models.ForeignKey(help_text='حساب معین', limit_choices_to={'account_level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='gl_account_relations', to='accounting.account')),
            ],
            options={
                'verbose_name': 'رابطه معین-کل',
                'verbose_name_plural': 'روابط معین-کل',
                'ordering': ('company', 'sub_account', '-is_primary', 'gl_account'),
            },
        ),
        migrations.AddConstraint(
            model_name='tafsilisubaccountrelation',
            constraint=models.UniqueConstraint(fields=('company', 'tafsili_account', 'sub_account'), name='accounting_tafsili_sub_relation_unique'),
        ),
        migrations.AddConstraint(
            model_name='subaccountglaccountrelation',
            constraint=models.UniqueConstraint(fields=('company', 'sub_account', 'gl_account'), name='accounting_sub_gl_relation_unique'),
        ),
    ]
