# Generated by Django 4.2 on 2025-12-01 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0014_add_editable_model_fields'),
        ('accounting', '0004_add_account_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafsiliHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('code', models.CharField(help_text='کد تفصیلی چند سطحی (یکتا در شرکت)', max_length=50, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('name', models.CharField(help_text='نام تفصیلی چند سطحی', max_length=200)),
                ('name_en', models.CharField(blank=True, help_text='نام تفصیلی چند سطحی (انگلیسی)', max_length=200)),
                ('level', models.PositiveSmallIntegerField(default=1, editable=False, help_text='سطح در درخت (1=ریشه، 2=زیرگروه اول، ...)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش')),
                ('description', models.TextField(blank=True, help_text='توضیحات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='تفصیلی چند سطحی والد (برای ساختار درختی)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.tafsilihierarchy')),
                ('tafsili_account', models.ForeignKey(blank=True, help_text='تفصیلی اصلی مرتبط (اختیاری - برای ریشه\u200cهای درخت)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchies', to='accounting.account')),
            ],
            options={
                'verbose_name': 'تفصیلی چند سطحی',
                'verbose_name_plural': 'تفصیلی\u200cهای چند سطحی',
                'ordering': ('company', 'level', 'sort_order', 'code'),
            },
        ),
        migrations.AddConstraint(
            model_name='tafsilihierarchy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='accounting_tafsili_hierarchy_code_unique'),
        ),
    ]
