# Generated by Django 4.2 on 2025-12-01 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_add_editable_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_add_tafsili_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('document_number', models.CharField(blank=True, help_text='شماره سند (برای جستجو و فیلتر)', max_length=50)),
                ('file', models.FileField(help_text='فایل پیوست', upload_to='accounting/documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('INVOICE', 'فاکتور'), ('RECEIPT', 'رسید'), ('CONTRACT', 'قرارداد'), ('CHECK', 'چک'), ('OTHER', 'سایر')], default='OTHER', help_text='نوع فایل', max_length=30)),
                ('file_name', models.CharField(help_text='نام اصلی فایل', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='حجم فایل به بایت')),
                ('mime_type', models.CharField(blank=True, help_text='نوع MIME فایل', max_length=100)),
                ('description', models.TextField(blank=True, help_text='توضیحات فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان آپلود')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='سند حسابداری مرتبط (اختیاری)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.accountingdocument')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='کاربری که فایل را آپلود کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیوست سند',
                'verbose_name_plural': 'پیوست\u200cهای اسناد',
                'ordering': ('company', '-uploaded_at', 'document_number'),
            },
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['company', 'document'], name='acc_attach_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['company', 'document_number'], name='acc_attach_docnum_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['company', 'file_type'], name='acc_attach_type_idx'),
        ),
    ]
