# Generated by Django 4.2 on 2025-12-02 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_add_editable_model_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_add_document_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('category_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], help_text='Type of category: income or expense', max_length=20)),
                ('category_code', models.CharField(blank=True, editable=False, help_text='Category code (auto-generated if not provided)', max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('category_name', models.CharField(help_text='Category name (Persian)', max_length=200)),
                ('category_name_en', models.CharField(blank=True, help_text='Category name (English)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description and notes about this category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی درآمد/هزینه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای درآمد/هزینه',
                'ordering': ('company', 'category_type', 'sort_order', 'category_code'),
            },
        ),
        migrations.AddConstraint(
            model_name='incomeexpensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'category_type', 'category_code'), name='accounting_income_expense_category_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='incomeexpensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'category_type', 'category_name'), name='accounting_income_expense_category_name_unique'),
        ),
    ]
