# Generated by Django 4.2 on 2025-12-03 07:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0024_bom_editing_by_bom_editing_session_key_and_more'),
        ('shared', '0014_add_editable_model_fields'),
        ('accounting', '0009_add_treasury_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('cost_center_code', models.CharField(blank=True, editable=False, help_text='Cost center code (auto-generated if not provided)', max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('cost_center_name', models.CharField(help_text='Cost center name (Persian)', max_length=200)),
                ('cost_center_name_en', models.CharField(blank=True, help_text='Cost center name (English)', max_length=200)),
                ('company_unit_code', models.CharField(blank=True, editable=False, help_text='Cached company unit code', max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('work_line_code', models.CharField(blank=True, editable=False, help_text='Cached work line code', max_length=5, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('description', models.TextField(blank=True, help_text='Description and notes about this cost center')),
            ],
            options={
                'verbose_name': 'مرکز هزینه',
                'verbose_name_plural': 'مراکز هزینه',
                'ordering': ('company', 'sort_order', 'cost_center_code'),
            },
        ),
        migrations.AlterModelOptions(
            name='accountingdocumentline',
            options={'ordering': ('company', 'document', 'sort_order', 'line_number'), 'verbose_name': 'Accounting Document Line', 'verbose_name_plural': 'Accounting Document Lines'},
        ),
        migrations.RemoveConstraint(
            model_name='accountingdocumentline',
            name='accounting_document_line_debit_or_credit',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='cost_center_id',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='party_id',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='GL Account (کل)', limit_choices_to={'account_level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_gl', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sort order for display'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='sub_account',
            field=models.ForeignKey(blank=True, help_text='Sub Account (معین) - Optional', limit_choices_to={'account_level': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_sub', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='tafsili_account',
            field=models.ForeignKey(blank=True, help_text='Tafsili Account (تفصیلی) - Optional', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_tafsili', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingdocumentline',
            name='description',
            field=models.CharField(blank=True, help_text='Line item description', max_length=255),
        ),
        migrations.AlterField(
            model_name='tafsilisubaccountrelation',
            name='tafsili_account',
            field=models.ForeignKey(help_text='حساب تفصیلی', limit_choices_to={'account_level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_sub_relations', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='company_code',
            field=models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AddConstraint(
            model_name='accountingdocumentline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='accounting_document_line_debit_or_credit'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='company_unit',
            field=models.ForeignKey(help_text='Organizational unit this cost center belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='shared.companyunit'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='work_line',
            field=models.ForeignKey(blank=True, help_text='Production work line this cost center is associated with (optional - only if production module is installed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='production.workline'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'cost_center_code'), name='accounting_cost_center_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'cost_center_name'), name='accounting_cost_center_name_unique'),
        ),
    ]
