# Generated by Django 4.2 on 2025-12-14 19:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_add_primary_groups_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0010_add_warehouse_transfer_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseIncomeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('document_code', models.CharField(editable=False, help_text='Auto-generated document code', max_length=30, unique=True)),
                ('issue_type', models.CharField(choices=[('PERMANENT', 'Permanent Issue'), ('CONSUMPTION', 'Consumption Issue'), ('CONSIGNMENT', 'Consignment Issue')], help_text='Type of issue this income document is linked to', max_length=20)),
                ('issue_id', models.BigIntegerField(help_text='ID of the issue document')),
                ('issue_code', models.CharField(help_text='Code of the issue document', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Document status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('accounting_document', models.ForeignKey(blank=True, help_text='Linked accounting document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_income_documents', to='accounting.accountingdocument')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Income Document',
                'verbose_name_plural': 'Warehouse Income Documents',
                'ordering': ('-document_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WarehouseExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('document_code', models.CharField(editable=False, help_text='Auto-generated document code', max_length=30, unique=True)),
                ('receipt_type', models.CharField(choices=[('PERMANENT', 'Permanent Receipt'), ('TEMPORARY', 'Temporary Receipt'), ('CONSIGNMENT', 'Consignment Receipt')], help_text='Type of receipt this expense document is linked to', max_length=20)),
                ('receipt_id', models.BigIntegerField(help_text='ID of the receipt document')),
                ('receipt_code', models.CharField(help_text='Code of the receipt document', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expense amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Document status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('accounting_document', models.ForeignKey(blank=True, help_text='Linked accounting document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_expense_documents', to='accounting.accountingdocument')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Expense Document',
                'verbose_name_plural': 'Warehouse Expense Documents',
                'ordering': ('-document_date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='warehouseincomedocument',
            index=models.Index(fields=['company', 'issue_type', 'issue_id'], name='warehouse_inc_issue_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseincomedocument',
            index=models.Index(fields=['company', 'status'], name='warehouse_inc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseexpensedocument',
            index=models.Index(fields=['company', 'receipt_type', 'receipt_id'], name='warehouse_exp_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseexpensedocument',
            index=models.Index(fields=['company', 'status'], name='warehouse_exp_status_idx'),
        ),
    ]
