# Generated by Django 4.2 on 2025-12-14 19:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_add_item_supply_planning_fields'),
        ('shared', '0015_add_primary_groups_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0011_warehouseincomedocument_warehouseexpensedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseExpenseDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(help_text='Item code from receipt line', max_length=16)),
                ('warehouse_code', models.CharField(blank=True, help_text='Warehouse code from receipt line', max_length=5)),
                ('unit', models.CharField(help_text='Unit used in receipt (entered_unit if exists, otherwise unit)', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Quantity in the unit used in receipt', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (in the unit used in receipt)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('base_unit', models.CharField(help_text="Item's default unit", max_length=30)),
                ('base_unit_price', models.DecimalField(decimal_places=2, help_text='Price per base unit (converted from unit_price)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this line (quantity * unit_price)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_notes', models.TextField(blank=True, help_text='Line notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.warehouseexpensedocument')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_expense_lines', to='inventory.item')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_expense_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Expense Document Line',
                'verbose_name_plural': 'Warehouse Expense Document Lines',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='warehouseexpensedocumentline',
            index=models.Index(fields=['company', 'document'], name='warehouse_exp_line_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseexpensedocumentline',
            index=models.Index(fields=['company', 'item'], name='warehouse_exp_line_item_idx'),
        ),
    ]
