# Generated by Django 4.2 on 2025-12-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_remove_account_type_normal_balance_from_gl_accounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='accounting_account_code_unique',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('ASSET', 'دارایی'), ('LIABILITY', 'بدهی'), ('EQUITY', 'حقوق صاحبان سهام'), ('REVENUE', 'درآمد'), ('EXPENSE', 'هزینه')], help_text='نوع حساب (در سند حسابداری تعریف می\u200cشود)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], help_text='طرف تراز مورد انتظار (در سند حسابداری تعریف می\u200cشود)', max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'account_code', 'account_level'), name='accounting_account_code_unique'),
        ),
    ]
