# Generated by Django 4.2 on 2025-12-15 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0015_add_primary_groups_to_user'),
        ('accounting', '0014_change_account_code_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafsiliType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('public_code', models.CharField(help_text='کد عمومی نوع تفصیلی', max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('name', models.CharField(help_text='نام نوع تفصیلی (فارسی)', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='نام نوع تفصیلی (انگلیسی)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='توضیحات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوع تفصیلی',
                'verbose_name_plural': 'انواع تفصیلی',
                'ordering': ('company', 'sort_order', 'public_code'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tafsili_type',
            field=models.ForeignKey(blank=True, help_text='نوع تفصیلی (فقط برای حساب\u200cهای تفصیلی)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tafsili_accounts', to='accounting.tafsilitype'),
        ),
        migrations.AddConstraint(
            model_name='tafsilitype',
            constraint=models.UniqueConstraint(fields=('company', 'public_code'), name='accounting_tafsili_type_company_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='tafsilitype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='accounting_tafsili_type_company_name_unique'),
        ),
    ]
