# Generated by Django 4.2 on 2025-12-27 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_add_primary_groups_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0016_seed_initial_tafsili_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalMemoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('fiscal_id', models.CharField(help_text='شناسه یکتای حافظه مالیاتی (Fiscal ID)', max_length=50)),
                ('name', models.CharField(help_text='نام/توضیحات حافظه مالیاتی', max_length=200)),
                ('server_url', models.URLField(default='https://tp.tax.gov.ir', help_text='آدرس سرور سامانه مودیان')),
                ('is_enabled', models.SmallIntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')], default=1, help_text='وضعیت فعال/غیرفعال')),
                ('api_timeout', models.IntegerField(default=30, help_text='مدت زمان انتظار برای پاسخ API (ثانیه)')),
                ('max_retry_count', models.IntegerField(default=3, help_text='حداکثر تعداد تلاش مجدد در صورت خطا')),
                ('private_key', models.TextField(blank=True, help_text='کلید خصوصی برای امضای دیجیتال')),
                ('public_key', models.TextField(blank=True, help_text='کلید عمومی برای تبادل با سامانه')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cها و توضیحات اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیکربندی حافظه مالیاتی',
                'verbose_name_plural': 'پیکربندی\u200cهای حافظه مالیاتی',
                'ordering': ('company', 'fiscal_id'),
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('submission_status', models.CharField(choices=[('PENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده'), ('ACCEPTED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('FAILED', 'خطا در ارسال'), ('RETRYING', 'در حال تلاش مجدد')], default='PENDING', help_text='وضعیت ارسال', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, help_text='تاریخ و زمان ارسال', null=True)),
                ('response_uid', models.CharField(blank=True, help_text='شناسه یکتای پاسخ از سامانه (UID)', max_length=100)),
                ('response_code', models.CharField(blank=True, help_text='کد پاسخ از سامانه', max_length=50)),
                ('response_message', models.TextField(blank=True, help_text='پیام پاسخ از سامانه')),
                ('response_timestamp', models.BigIntegerField(blank=True, help_text='Timestamp پاسخ از سامانه', null=True)),
                ('invoice_data', models.JSONField(default=dict, help_text='داده\u200cهای صورتحساب (JSON format)')),
                ('retry_count', models.IntegerField(default=0, help_text='تعداد تلاش\u200cهای انجام شده')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='زمان آخرین تلاش مجدد', null=True)),
                ('error_code', models.CharField(blank=True, help_text='کد خطا (در صورت وجود)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='پیام خطا')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cها و توضیحات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ارسال صورتحساب به سامانه مودیان',
                'verbose_name_plural': 'ارسال\u200cهای صورتحساب به سامانه مودیان',
                'ordering': ('-submission_date', '-created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='accountingdocument',
            name='is_locked',
        ),
        migrations.CreateModel(
            name='TaxInvoiceSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('log_type', models.CharField(choices=[('SUBMIT', 'ارسال'), ('RESPONSE', 'پاسخ'), ('RETRY', 'تلاش مجدد'), ('ERROR', 'خطا'), ('VALIDATION', 'اعتبارسنجی')], help_text='نوع لاگ', max_length=20)),
                ('log_message', models.TextField(help_text='پیام لاگ')),
                ('request_data', models.JSONField(blank=True, help_text='داده\u200cهای درخواست (JSON)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='داده\u200cهای پاسخ (JSON)', null=True)),
                ('http_status_code', models.IntegerField(blank=True, help_text='کد وضعیت HTTP', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='زمان اجرا (ثانیه)', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربر ایجادکننده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_submission_logs', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='ارسال مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounting.taxinvoicesubmission')),
            ],
            options={
                'verbose_name': 'لاگ ارسال صورتحساب',
                'verbose_name_plural': 'لاگ\u200cهای ارسال صورتحساب',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='taxinvoicesubmission',
            name='document',
            field=models.ForeignKey(help_text='سند حسابداری مرتبط', on_delete=django.db.models.deletion.PROTECT, related_name='tax_submissions', to='accounting.accountingdocument'),
        ),
        migrations.AddField(
            model_name='taxinvoicesubmission',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxinvoicesubmission',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxinvoicesubmission',
            name='fiscal_memory',
            field=models.ForeignKey(help_text='حافظه مالیاتی استفاده شده', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_submissions', to='accounting.fiscalmemoryconfig'),
        ),
        migrations.AddIndex(
            model_name='taxinvoicesubmissionlog',
            index=models.Index(fields=['submission', 'log_type'], name='accounting__submiss_f368f9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoicesubmissionlog',
            index=models.Index(fields=['created_at'], name='accounting__created_aac46f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoicesubmission',
            index=models.Index(fields=['document', 'submission_status'], name='accounting__documen_07622a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoicesubmission',
            index=models.Index(fields=['fiscal_memory', 'submission_status'], name='accounting__fiscal__794067_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoicesubmission',
            index=models.Index(fields=['response_uid'], name='accounting__respons_bb8366_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalmemoryconfig',
            constraint=models.UniqueConstraint(fields=('company', 'fiscal_id'), name='accounting_fiscalmemory_company_fiscalid_unique'),
        ),
    ]
