# Generated by Django 4.2 on 2025-12-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_fiscalmemoryconfig_taxinvoicesubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalmemoryconfig',
            name='encryption_type',
            field=models.CharField(choices=[('AES-256', 'AES-256'), ('AES-128', 'AES-128'), ('RSA-2048', 'RSA-2048')], default='AES-256', help_text='نوع رمزگذاری', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscalmemoryconfig',
            name='private_key_password',
            field=models.CharField(blank=True, help_text='رمز عبور کلید خصوصی (در صورت نیاز)', max_length=200),
        ),
        migrations.AddField(
            model_name='fiscalmemoryconfig',
            name='signature_type',
            field=models.CharField(choices=[('PKCS#7', 'PKCS#7'), ('RSA', 'RSA'), ('ECDSA', 'ECDSA')], default='PKCS#7', help_text='نوع امضای دیجیتال', max_length=50),
        ),
    ]
