# Generated by Django 4.2 on 2025-12-27 09:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0019_convert_tafsili_hierarchy_to_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('is_locked', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('request_code', models.CharField(max_length=30, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('purchase_invoice', 'Purchase Invoice'), ('service_invoice', 'Service Invoice'), ('direct_expense', 'Direct Expense'), ('prepayment', 'Prepayment'), ('other', 'Other')], help_text='Type of payment request', max_length=30)),
                ('request_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested payment amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('party_code', models.CharField(blank=True, max_length=10)),
                ('purchase_invoice_code', models.CharField(blank=True, max_length=20)),
                ('service_invoice_code', models.CharField(blank=True, max_length=20)),
                ('expense_category_code', models.CharField(blank=True, max_length=30)),
                ('expense_description', models.TextField(blank=True, help_text='Description of expense (for direct expense payments)')),
                ('prepayment_account_code', models.CharField(blank=True, max_length=30)),
                ('treasury_transaction_id', models.BigIntegerField(blank=True, help_text='Related treasury transaction ID (created when paid)', null=True)),
                ('treasury_transaction_number', models.CharField(blank=True, max_length=30)),
                ('accounting_document_number', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('document_metadata', models.JSONField(blank=True, default=dict)),
                ('accounting_document', models.ForeignKey(blank=True, help_text='Related accounting document (created when paid)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='accounting.accountingdocument')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('expense_category', models.ForeignKey(blank=True, help_text='Expense category (for direct expense payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='accounting.incomeexpensecategory')),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Fiscal year for this document (auto-populated from document_date)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounting.fiscalyear')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, help_text='Party to pay (supplier, vendor, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounting.party')),
                ('prepayment_account', models.ForeignKey(blank=True, help_text='Prepayment account (for prepayment payments)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_payment_requests', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ('-request_date', '-request_code'),
            },
        ),
    ]
