# Generated by Django 4.2 on 2025-12-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('accounting', '0020_paymentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, help_text='Related purchase invoice (if payment_type = purchase_invoice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='procurement.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='service_invoice',
            field=models.ForeignKey(blank=True, help_text='Related service invoice (if payment_type = service_invoice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='procurement.serviceinvoice'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_unlocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'request_date'], name='acc_payreq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'party'], name='acc_payreq_party_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'purchase_invoice'], name='acc_payreq_pinv_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['company', 'service_invoice'], name='acc_payreq_sinv_idx'),
        ),
    ]
