# Generated by Django 4.2 on 2025-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_paymentrequest_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment', null=True),
        ),
    ]
