# Generated by Django 4.2 on 2025-12-30 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0023_automation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='incomeexpensecategory',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeexpensecategory',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='incomeexpensecategory',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='party',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='partyaccount',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyaccount',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='partyaccount',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='tafsilitype',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tafsilitype',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='tafsilitype',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
        migrations.AddField(
            model_name='warehouseexpensedocumentline',
            name='editing_by',
            field=models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseexpensedocumentline',
            name='editing_session_key',
            field=models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40),
        ),
        migrations.AddField(
            model_name='warehouseexpensedocumentline',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, help_text='When editing session started', null=True),
        ),
    ]
