# Generated by Django 4.2 on 2025-12-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_add_editable_model_to_accounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treasuryaccount',
            name='accounting_treasury_account_tafsili_unique',
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='sub_account',
            field=models.ForeignKey(blank=True, help_text='معین حساب (یا تفصیلی یا معین باید انتخاب شود)', limit_choices_to={'account_level': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts_as_sub', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='tafsili_account',
            field=models.ForeignKey(blank=True, help_text='تفصیلی حساب (یا تفصیلی یا معین باید انتخاب شود)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('tafsili_account__isnull', False)), fields=('company', 'tafsili_account'), name='accounting_treasury_account_tafsili_unique'),
        ),
    ]
