# Generated by Django 4.2 on 2025-12-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_remove_treasuryaccount_accounting_treasury_account_tafsili_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='tafsili_level',
            field=models.ForeignKey(blank=True, help_text='سطح تفصیلی (یا سطح تفصیلی یا معین باید انتخاب شود)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.tafsilihierarchy'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='sub_account',
            field=models.ForeignKey(blank=True, help_text='معین حساب (یا سطح تفصیلی یا معین باید انتخاب شود)', limit_choices_to={'account_level': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts_as_sub', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='tafsili_account',
            field=models.ForeignKey(blank=True, editable=False, help_text='حساب تفصیلی (خودکار ساخته می\u200cشود)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account'),
        ),
    ]
