# Generated by Django 4.2 on 2025-12-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_treasuryaccount_tafsili_level_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treasuryaccount',
            name='accounting_treasury_account_tafsili_unique',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='sub_account',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='tafsili_level',
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='tafsili_account',
            field=models.ForeignKey(blank=True, help_text='حساب تفصیلی (فقط تفصیلی\u200cهای قابل استفاده در فروش)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account'),
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(fields=('company', 'tafsili_account'), name='accounting_treasury_account_tafsili_unique'),
        ),
    ]
