# Generated by Django 4.2 on 2026-01-03 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0016_add_entity_type_to_company'),
        ('accounting', '0027_remove_treasuryaccount_accounting_treasury_account_tafsili_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('editing_started_at', models.DateTimeField(blank=True, help_text='When editing session started', null=True)),
                ('editing_session_key', models.CharField(blank=True, help_text='Django session key of the editing user', max_length=40)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('group_code', models.CharField(help_text="کد گروه حساب (مثال: '1' برای دارایی\u200cهای جاری)", max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('group_name', models.CharField(help_text='نام گروه حساب (فارسی)', max_length=200)),
                ('group_name_en', models.CharField(blank=True, help_text='نام گروه حساب (انگلیسی)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='توضیحات گروه حساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('editing_by', models.ForeignKey(blank=True, help_text='User currently editing this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_editing', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گروه حساب',
                'verbose_name_plural': 'گروه\u200cهای حساب',
                'ordering': ('company', 'group_code'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(blank=True, help_text='گروه حساب (فقط برای حساب\u200cهای کل)', limit_choices_to={'is_enabled': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountgroup'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('company', 'group_code'), name='accounting_account_group_code_unique'),
        ),
    ]
