# Generated by Django 4.2 on 2026-01-04 12:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0028_add_account_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccountTafsiliTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'سطح 1'), (2, 'سطح 2'), (3, 'سطح 3')], help_text='سطح تفصیلی (1 تا 3)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رابطه معین-نوع تفصیلی',
                'verbose_name_plural': 'روابط معین-نوع تفصیلی',
                'ordering': ('company', 'sub_account', 'level', 'tafsili_type'),
            },
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='enabled_by',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='sub_account',
        ),
        migrations.RemoveField(
            model_name='tafsililevelsubaccountrelation',
            name='tafsili_level',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='enabled_by',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='sub_account',
        ),
        migrations.RemoveField(
            model_name='tafsilisubaccountrelation',
            name='tafsili_account',
        ),
        migrations.AddField(
            model_name='account',
            name='is_tafsili_enabled',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='تفصیل پذیر (فقط برای حساب\u200cهای معین)'),
        ),
        migrations.AddField(
            model_name='account',
            name='tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح 1'), (2, 'سطح 2'), (3, 'سطح 3')], help_text='سطح تفصیلی (1 تا 3) - فقط برای حساب\u200cهای تفصیلی', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.CharField(help_text="کد حساب (مثال: '11' برای حساب کل، '1101' برای معین)", max_length=20, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.DeleteModel(
            name='TafsiliHierarchy',
        ),
        migrations.DeleteModel(
            name='TafsiliLevelSubAccountRelation',
        ),
        migrations.DeleteModel(
            name='TafsiliSubAccountRelation',
        ),
        migrations.AddField(
            model_name='subaccounttafsilityperelation',
            name='sub_account',
            field=models.ForeignKey(help_text='حساب معین', limit_choices_to={'account_level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_type_relations', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='subaccounttafsilityperelation',
            name='tafsili_type',
            field=models.ForeignKey(help_text='نوع تفصیلی', on_delete=django.db.models.deletion.CASCADE, related_name='sub_account_relations', to='accounting.tafsilitype'),
        ),
        migrations.AddConstraint(
            model_name='subaccounttafsilityperelation',
            constraint=models.UniqueConstraint(fields=('company', 'sub_account', 'tafsili_type', 'level'), name='accounting_sub_tafsili_type_level_unique'),
        ),
    ]
