# Generated by Django 4.2 on 2026-01-04 12:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0029_restructure_tafsili_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafsiliSubAccountRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('is_primary', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='حساب معین اصلی (برای نمایش پیش\u200cفرض)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('sub_account', models.ForeignKey(help_text='حساب معین', limit_choices_to={'account_level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_account_relations', to='accounting.account')),
                ('tafsili_account', models.ForeignKey(help_text='حساب تفصیلی', limit_choices_to={'account_level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_account_relations_as_tafsili', to='accounting.account')),
            ],
            options={
                'verbose_name': 'رابطه تفصیلی-معین',
                'verbose_name_plural': 'روابط تفصیلی-معین',
                'ordering': ('company', 'tafsili_account', '-is_primary', 'sub_account'),
            },
        ),
        migrations.AddConstraint(
            model_name='tafsilisubaccountrelation',
            constraint=models.UniqueConstraint(fields=('company', 'tafsili_account', 'sub_account'), name='accounting_tafsili_sub_relation_unique'),
        ),
    ]
