# Generated by Django 4.2 on 2026-01-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_tafsilisubaccountrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='accountingdocumentline',
            name='tafsili_account',
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='tafsili_level_1',
            field=models.ForeignKey(blank=True, help_text='Tafsili Level 1 (تفصیلی سطح ۱)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_tafsili_1', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='tafsili_level_2',
            field=models.ForeignKey(blank=True, help_text='Tafsili Level 2 (تفصیلی سطح ۲)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_tafsili_2', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingdocumentline',
            name='tafsili_level_3',
            field=models.ForeignKey(blank=True, help_text='Tafsili Level 3 (تفصیلی سطح ۳)', limit_choices_to={'account_level': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_tafsili_3', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='accountingdocumentline',
            name='sub_account',
            field=models.ForeignKey(blank=True, help_text='Sub Account (معین)', limit_choices_to={'account_level': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines_as_sub', to='accounting.account'),
        ),
    ]
