# Generated by Django 4.2 on 2026-01-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_update_document_line_tafsili_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='customer_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='سطح تفصیلی مشتری (فقط برای مشتریان)', null=True, verbose_name='سطح تفصیلی مشتری'),
        ),
    ]
