# Generated by Django 4.2 on 2026-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_add_customer_tafsili_level_to_party'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='accounting_party_name_unique',
        ),
        migrations.RemoveField(
            model_name='party',
            name='party_name',
        ),
        migrations.AddField(
            model_name='party',
            name='first_name',
            field=models.CharField(default='', help_text='First name (Persian)', max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='party',
            name='last_name',
            field=models.CharField(default='', help_text='Last name (Persian)', max_length=100, verbose_name='نام خانوادگی'),
        ),
    ]
