# Generated by Django 4.2 on 2026-01-06 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0033_add_first_last_name_to_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='customer_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='', null=True, verbose_name='نوع مشتری'),
        ),
        migrations.CreateModel(
            name='TafsiliAccountHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('level_depth', models.PositiveSmallIntegerField(default=1, help_text='عمق رابطه در درخت (۱=مستقیم، ۲=نوه، ...)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='ترتیب نمایش در لیست')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('child_account', models.ForeignKey(help_text='حساب تفصیلی فرزند (child)', limit_choices_to={'account_level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_parents', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(help_text='حساب تفصیلی والد (parent)', limit_choices_to={'account_level': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'رابطه سلسله مراتبی تفصیلی',
                'verbose_name_plural': 'روابط سلسله مراتبی تفصیلی',
                'ordering': ('company', 'sort_order', 'parent_account', 'child_account'),
            },
        ),
        migrations.AddConstraint(
            model_name='tafsiliaccounthierarchy',
            constraint=models.UniqueConstraint(fields=('company', 'parent_account', 'child_account'), name='accounting_tafsili_hierarchy_unique'),
        ),
    ]
