# Generated by Django 4.2 on 2026-01-06 15:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0034_add_tafsili_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='customer_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='', null=True, verbose_name='نوع مشتری'),
        ),
        migrations.CreateModel(
            name='SubAccountTafsiliLevel1Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('is_primary', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=0, help_text='حساب تفصیلی سطح ۱ اصلی (برای نمایش پیش\u200cفرض)')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('sub_account', models.ForeignKey(help_text='حساب معین', limit_choices_to={'account_level': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_level1_relations', to='accounting.account')),
                ('tafsili_level1_account', models.ForeignKey(help_text='حساب تفصیلی سطح ۱', limit_choices_to={'account_level': 3, 'tafsili_level': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_account_level1_relations', to='accounting.account')),
            ],
            options={
                'verbose_name': 'رابطه معین-تفصیلی سطح ۱',
                'verbose_name_plural': 'روابط معین-تفصیلی سطح ۱',
                'ordering': ('company', 'sub_account', '-is_primary', 'tafsili_level1_account'),
            },
        ),
        migrations.AddConstraint(
            model_name='subaccounttafsililevel1relation',
            constraint=models.UniqueConstraint(fields=('company', 'sub_account', 'tafsili_level1_account'), name='accounting_sub_tafsili_level1_relation_unique'),
        ),
    ]
