# Generated by Django 4.2 on 2026-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_add_subaccount_tafsili_level1_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='customer_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='', null=True, verbose_name='نوع مشتری'),
        ),
    ]
