# Generated by Django 4.2 on 2025-12-26 17:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0015_add_primary_groups_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0045_add_item_supply_planning_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company_code', models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')])),
                ('item_code', models.CharField(editable=False, help_text='Cached item code', max_length=16, verbose_name='Item Code')),
                ('price', models.DecimalField(decimal_places=6, help_text='Item price', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('currency', models.CharField(choices=[('IRT', 'Toman'), ('IRR', 'Rial'), ('USD', 'US Dollar')], default='IRT', max_length=10, verbose_name='Currency')),
                ('effective_date', models.DateField(blank=True, help_text='Date when this price becomes effective', null=True, verbose_name='Effective Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when this price expires', null=True, verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_cards', to='inventory.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item Price Card',
                'verbose_name_plural': 'Item Price Cards',
                'ordering': ('company', 'sort_order', 'item_code'),
            },
        ),
        migrations.AddConstraint(
            model_name='itempricecard',
            constraint=models.UniqueConstraint(fields=('company', 'item'), name='sales_item_price_card_unique'),
        ),
    ]
