# Generated by Django 4.2 on 2025-12-27 11:35

from django.db import migrations, models
import django.db.models.deletion


def set_tafsili_levels_to_null(apps, schema_editor):
    """Set all tafsili level fields to NULL before converting to ForeignKey."""
    SalesSettings = apps.get_model('sales', 'SalesSettings')
    # Use raw SQL to bypass model constraints
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE sales_salessettings SET customer_tafsili_level = NULL, bank_tafsili_level = NULL, check_tafsili_level = NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_add_due_date_to_payment_request'),
        ('sales', '0002_salessettings_and_more'),
    ]

    operations = [
        # First, make fields nullable
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='سطح تفصیلی مشتری\u200cها', null=True, verbose_name='Customer Tafsili Level'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='bank_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='سطح تفصیلی بانک\u200cها', null=True, verbose_name='Bank Tafsili Level'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='check_tafsili_level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='سطح تفصیلی چک\u200cها', null=True, verbose_name='Check Tafsili Level'),
        ),
        # Set all values to NULL
        migrations.RunPython(set_tafsili_levels_to_null, migrations.RunPython.noop),
        # Then, change field types to ForeignKey
        migrations.AlterField(
            model_name='salessettings',
            name='bank_tafsili_level',
            field=models.ForeignKey(blank=True, help_text='سطح تفصیلی بانک\u200cها', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_settings_as_bank', to='accounting.tafsilihierarchy', verbose_name='Bank Tafsili Level'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='check_tafsili_level',
            field=models.ForeignKey(blank=True, help_text='سطح تفصیلی چک\u200cها', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_settings_as_check', to='accounting.tafsilihierarchy', verbose_name='Check Tafsili Level'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level',
            field=models.ForeignKey(blank=True, help_text='سطح تفصیلی مشتری\u200cها', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_settings_as_customer', to='accounting.tafsilihierarchy', verbose_name='Customer Tafsili Level'),
        ),
    ]
