# Generated by Django 4.2 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_add_due_date_to_payment_request'),
        ('sales', '0003_alter_salessettings_bank_tafsili_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeReceiptLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Edited At')),
                ('is_enabled', models.PositiveSmallIntegerField(default=1, help_text='Active status (1=active, 0=inactive)', verbose_name='Is Enabled')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', verbose_name='Metadata')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order for display', verbose_name='Sort Order')),
                ('treasury_account', models.ForeignKey(help_text='حساب نقدی یا بانکی برای دریافت درآمد', on_delete=django.db.models.deletion.PROTECT, related_name='income_receipt_locations', to='accounting.treasuryaccount', verbose_name='Treasury Account')),
                ('receipt_method', models.CharField(choices=[('pos', 'پوز'), ('cash', 'نقد'), ('account', 'حساب'), ('check', 'چک'), ('paya', 'پایا'), ('satna', 'ساتنا'), ('pay', 'پل'), ('multiple', 'چند مورد با هم')], help_text='روش دریافت درآمد', max_length=50, verbose_name='Receipt Method')),
                ('location_name', models.CharField(help_text='نام محل دریافت درآمد', max_length=200, verbose_name='Location Name')),
                ('notes', models.TextField(blank=True, help_text='توضیحات و یادداشت\u200cها', verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='shared.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Income Receipt Location',
                'verbose_name_plural': 'Income Receipt Locations',
                'ordering': ('company', 'sort_order', 'location_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='incomereceiptlocation',
            constraint=models.UniqueConstraint(fields=('company', 'treasury_account', 'receipt_method', 'location_name'), name='sales_income_receipt_location_unique'),
        ),
    ]

