# Generated by Django 4.2 on 2025-12-30 17:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_add_entity_type_to_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_incomereceiptlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='company_code',
            field=models.CharField(blank=True, editable=False, max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_disabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomereceiptlocation',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_enabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='shared.company'),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='is_enabled',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='incomereceiptlocation',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
