# Generated by Django 4.2 on 2026-01-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_incomereceiptlocation_company_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessettings',
            name='bank_tafsili_level',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='check_tafsili_level',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='customer_tafsili_level',
        ),
    ]
