# Generated by Django 4.2 on 2026-01-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_update_document_line_tafsili_levels'),
        ('sales', '0006_remove_salessettings_bank_tafsili_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_1',
            field=models.ForeignKey(blank=True, help_text='حساب تفصیلی سطح ۱ برای مشتریان', limit_choices_to={'account_level': 3, 'is_enabled': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_1', to='accounting.account', verbose_name='سطح تفصیلی مشتری ۱'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_2',
            field=models.ForeignKey(blank=True, help_text='حساب تفصیلی سطح ۲ برای مشتریان', limit_choices_to={'account_level': 3, 'is_enabled': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_2', to='accounting.account', verbose_name='سطح تفصیلی مشتری ۲'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_3',
            field=models.ForeignKey(blank=True, help_text='حساب تفصیلی سطح ۳ برای مشتریان', limit_choices_to={'account_level': 3, 'is_enabled': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_3', to='accounting.account', verbose_name='سطح تفصیلی مشتری ۳'),
        ),
    ]
