# Generated by Django 4.2 on 2026-01-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_update_document_line_tafsili_levels'),
        ('sales', '0007_add_customer_tafsili_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_1',
            field=models.ForeignKey(blank=True, help_text='نوع تفصیلی سطح ۱ برای مشتریان', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_1', to='accounting.tafsilitype', verbose_name='نوع تفصیلی مشتری ۱'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_2',
            field=models.ForeignKey(blank=True, help_text='نوع تفصیلی سطح ۲ برای مشتریان', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_2', to='accounting.tafsilitype', verbose_name='نوع تفصیلی مشتری ۲'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_3',
            field=models.ForeignKey(blank=True, help_text='نوع تفصیلی سطح ۳ برای مشتریان', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_customer_level_3', to='accounting.tafsilitype', verbose_name='نوع تفصیلی مشتری ۳'),
        ),
    ]
