# Generated by Django 4.2 on 2026-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_change_customer_tafsili_to_tafsili_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_1_description',
            field=models.TextField(blank=True, help_text='توضیحات اضافی برای نوع تفصیلی سطح ۱ مشتریان', verbose_name='توضیحات سطح ۱'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_2_description',
            field=models.TextField(blank=True, help_text='توضیحات اضافی برای نوع تفصیلی سطح ۲ مشتریان', verbose_name='توضیحات سطح ۲'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_3_description',
            field=models.TextField(blank=True, help_text='توضیحات اضافی برای نوع تفصیلی سطح ۳ مشتریان', verbose_name='توضیحات سطح ۳'),
        ),
    ]
