# Generated by Django 4.2 on 2026-01-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_customer_tafsili_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_1_account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], default=1, help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۱', verbose_name='سطح حساب ۱'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_2_account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], default=2, help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۲', verbose_name='سطح حساب ۲'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='customer_tafsili_level_3_account_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], default=3, help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۳', verbose_name='سطح حساب ۳'),
        ),
    ]
