# Generated by Django 4.2 on 2026-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_add_customer_tafsili_account_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_1_account_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۱', null=True, verbose_name='سطح حساب ۱'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_2_account_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۲', null=True, verbose_name='سطح حساب ۲'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='customer_tafsili_level_3_account_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'سطح ۱'), (2, 'سطح ۲'), (3, 'سطح ۳')], help_text='سطح حساب تفصیلی برای نوع تفصیلی سطح ۳', null=True, verbose_name='سطح حساب ۳'),
        ),
    ]
